source 'https://rubygems.org'

gem 'rails', '7.0.4'
gem 'pg', '~> 1.5'
gem 'puma'
gem 'bootsnap', require: false # speed up boot

group :development, :test do
  gem 'rspec-rails', '6.0.1'
  gem 'pry'
end

group :test do
  gem 'capybara'
end
