package main

// cli_flags.go — generalized flag-parsing helper used by every
// `force <subcommand>` handler.
//
// Generalized from D12's parseDaemonFlags (which lived in daemon_help.go
// and only covered the daemon family). This file extends the same
// safety contract to the rest of the CLI surface.
//
// Each handler builds a *flag.FlagSet with usage text generated by
// printSubcommandHelp, then routes through parseSubcommandFlags which:
//
//   - intercepts --help / -h FIRST and exits 0 (so a discovery probe
//     never triggers a side-effect)
//   - rejects unknown flags with a non-zero exit + usage on stderr
//
// The fix closes a CLI-safety defect class found across the entire
// force CLI surface where, e.g., `force add-repo --bogus-flag` printed
// usage and exited 0 instead of rejecting. Every mutating handler now
// rejects unknown flags BEFORE any state is touched.
//
// flagDoc is the per-flag help-text descriptor. The legacy daemon
// helper used the same shape; we re-use it here so daemon callers can
// stay byte-identical.

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

// printSubcommandHelp writes the standard help block for a generic
// `force <name>` subcommand. Daemon subcommands route through
// printDaemonSubcommandHelp (kept as a thin wrapper) so the rendered
// "Usage: force daemon <name>" prefix is preserved.
func printSubcommandHelp(w io.Writer, name, desc string, flags []flagDoc, examples []string) {
	fmt.Fprintf(w, "Usage: force %s [flags]\n\n", name)
	if desc != "" {
		fmt.Fprintf(w, "%s\n\n", desc)
	}
	if len(flags) > 0 {
		fmt.Fprintln(w, "Flags:")
		width := 0
		for _, f := range flags {
			if len(f.Name) > width {
				width = len(f.Name)
			}
		}
		if width < 18 {
			width = 18
		}
		for _, f := range flags {
			fmt.Fprintf(w, "  %-*s  %s\n", width, f.Name, f.Desc)
		}
		fmt.Fprintln(w)
	}
	if len(examples) > 0 {
		fmt.Fprintln(w, "Examples:")
		for _, ex := range examples {
			fmt.Fprintf(w, "  %s\n", ex)
		}
	}
}

// parseSubcommandFlags wraps fs.Parse with two safety guarantees:
//
//  1. If args contains --help / -h anywhere before the first positional
//     token, print the subcommand's help to stdout and return
//     helpRequested=true so the caller can return 0 BEFORE any
//     side-effect.
//  2. Otherwise call fs.Parse, which (because fs is constructed with
//     flag.ContinueOnError) returns an error on unknown flags. On
//     error, we write usage to stderr and return parseErr so the
//     caller can return non-zero BEFORE any side-effect.
//
// The `name` is the human-readable subcommand label (e.g. "add-repo"
// or "daemon install") — printed in usage text and error prefixes.
//
// Returns: (helpRequested, parseErr). If helpRequested is true,
// parseErr is always nil. If parseErr is non-nil, helpRequested is
// false.
func parseSubcommandFlags(fs *flag.FlagSet, args []string, name, desc string, flagDocs []flagDoc, examples []string) (bool, error) {
	// Detect --help / -h before flag.Parse so we can route to our
	// shared helper rather than letting the FlagSet's own usage fire.
	for _, a := range args {
		if a == "--help" || a == "-h" || a == "help" {
			// Daemon subcommands historically render with the "force daemon <name>"
			// prefix. We keep that by detecting a leading "daemon " in name and
			// dispatching to the daemon-specific printer. All other subcommands
			// use the generic printer.
			if strings.HasPrefix(name, "daemon ") {
				printDaemonSubcommandHelp(os.Stdout, strings.TrimPrefix(name, "daemon "), desc, flagDocs, examples)
			} else {
				printSubcommandHelp(os.Stdout, name, desc, flagDocs, examples)
			}
			return true, nil
		}
		// Convention: stop scanning at the first non-flag positional
		// (mirrors POSIX getopt). This lets `force trust add <path>`
		// keep working without the path being mistaken for a flag.
		if !strings.HasPrefix(a, "-") {
			break
		}
		if a == "--" {
			break
		}
	}

	// Suppress flag.FlagSet's default Usage on error — we render our
	// own to keep the format consistent.
	fs.SetOutput(io.Discard)
	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "force %s: %v\n\n", name, err)
		if strings.HasPrefix(name, "daemon ") {
			printDaemonSubcommandHelp(os.Stderr, strings.TrimPrefix(name, "daemon "), desc, flagDocs, examples)
		} else {
			printSubcommandHelp(os.Stderr, name, desc, flagDocs, examples)
		}
		return false, err
	}
	return false, nil
}
