package main

// D12 — daemon subcommand help + unknown-flag rejection.
//
// Shared between every cmdDaemon<Name> handler. Each handler builds a
// *flag.FlagSet with usage text generated by printDaemonSubcommandHelp,
// then routes through parseDaemonFlags which:
//
//   - intercepts --help / -h FIRST and exits 0 (so a discovery probe
//     never triggers a side-effect)
//   - rejects unknown flags with a non-zero exit + usage on stderr
//
// The fix closes a CLI-safety defect found during D12 P4 verification
// where `force daemon install --help` silently ran the install (writing
// the launchd plist) because the handler ignored unrecognized tokens.

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

// flagDoc describes one flag for help-text rendering.
type flagDoc struct {
	Name string // e.g. "--dry-run" or "--binary <path>"
	Desc string // one-line description
}

// printDaemonSubcommandHelp writes the standard help block to w.
// Used by both the per-subcommand --help handler and the
// `force daemon help <sub>` surface.
func printDaemonSubcommandHelp(w io.Writer, name, desc string, flags []flagDoc, examples []string) {
	fmt.Fprintf(w, "Usage: force daemon %s [flags]\n\n", name)
	if desc != "" {
		fmt.Fprintf(w, "%s\n\n", desc)
	}
	if len(flags) > 0 {
		fmt.Fprintln(w, "Flags:")
		// Compute padding for alignment.
		width := 0
		for _, f := range flags {
			if len(f.Name) > width {
				width = len(f.Name)
			}
		}
		if width < 18 {
			width = 18
		}
		for _, f := range flags {
			fmt.Fprintf(w, "  %-*s  %s\n", width, f.Name, f.Desc)
		}
		fmt.Fprintln(w)
	}
	if len(examples) > 0 {
		fmt.Fprintln(w, "Examples:")
		for _, ex := range examples {
			fmt.Fprintf(w, "  %s\n", ex)
		}
	}
}

// parseDaemonFlags wraps fs.Parse with two safety guarantees:
//
//  1. If args contains --help / -h anywhere before parsing, print the
//     subcommand's help to stdout and return helpRequested=true so the
//     caller can return 0 BEFORE any side-effect.
//  2. Otherwise call fs.Parse, which (because fs is constructed with
//     flag.ContinueOnError) returns an error on unknown flags. On
//     error, we write usage to stderr and return parseErr so the
//     caller can return non-zero BEFORE any side-effect.
//
// Returns: (helpRequested, parseErr). If helpRequested is true, parseErr
// is always nil. If parseErr is non-nil, helpRequested is false.
func parseDaemonFlags(fs *flag.FlagSet, args []string, name, desc string, flagDocs []flagDoc, examples []string) (bool, error) {
	// Detect --help / -h before flag.Parse so we can route to our shared
	// helper rather than letting the FlagSet's own usage fire (which
	// would print the auto-generated form, then we'd have to mute it).
	for _, a := range args {
		if a == "--help" || a == "-h" || a == "help" {
			printDaemonSubcommandHelp(os.Stdout, name, desc, flagDocs, examples)
			return true, nil
		}
		// Convention: stop scanning at the first non-flag positional
		// (mirrors POSIX getopt). This lets `trust add <path>` keep
		// working without the path being mistaken for a flag.
		if !strings.HasPrefix(a, "-") {
			break
		}
		if a == "--" {
			break
		}
	}

	// Suppress flag.FlagSet's default Usage on error — we render our
	// own to keep the format consistent.
	fs.SetOutput(io.Discard)
	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "force daemon %s: %v\n\n", name, err)
		printDaemonSubcommandHelp(os.Stderr, name, desc, flagDocs, examples)
		return false, err
	}
	return false, nil
}
