package main

// onboard.go — D6 Synthetic Onboarding CLI.
//
// `force onboard <repo-spec>` produces a human-readable ONBOARDING.md
// at the target repo's root by reusing the Senator bootstrap pipeline's
// knowledge-synthesis step. <repo-spec> is either:
//
//   - a registered repo name (looked up via store.GetRepo), OR
//   - a path to a repo on disk.
//
// `force onboard --refresh <repo>` is operator-equivalent to a plain
// re-run; both regenerate ONBOARDING.md against current repo state.
// The flag exists so an operator can wire a cron job that says
// "explicitly intended a refresh" without having to remember whether
// the bare-form regenerates.
//
// Anti-cheat: this CLI MUST NOT duplicate the digest assembly. It
// consumes librarian.Client.BuildRepoDigest — the same method
// inprocess_d4.go's BootstrapSenatorRules uses. The AST audit
// TestOnboardingSynthesizesFromSenatorPipeline/AST_BothPathsCallBuildRepoDigest
// in cmd/force/onboard_test.go walks BOTH this file and inprocess_d4.go
// and asserts each references BuildRepoDigest. Editing this file to
// inline the digest assembly will trip the audit.

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"force-orchestrator/internal/clients/librarian"
)

// onboardingAutoGeneratedHeaderPrefix is the literal prefix of the
// AUTO-GENERATED comment stamped at the top of every ONBOARDING.md.
// The pre-commit hook compares the staged file's first line against
// this prefix to detect hand-edits — operators who hand-edit and
// then strip the header trip the comparison anyway because the file
// no longer round-trips through the renderer's stable shape.
const onboardingAutoGeneratedHeaderPrefix = "<!-- AUTO-GENERATED by `force onboard"

// cmdOnboard implements `force onboard <repo-spec> [--refresh]`.
//
// Exit codes:
//
//	0 — ONBOARDING.md was rendered (or refreshed)
//	1 — error (missing repo, write failure, etc.)
//	2 — usage error (bad flags / missing arg)
func cmdOnboard(ctx context.Context, db *sql.DB, args []string) {
	fs := flag.NewFlagSet("onboard", flag.ContinueOnError)
	refreshFlag := fs.Bool("refresh", false, "regenerate the ONBOARDING.md (idempotent)")
	helped, perr := parseSubcommandFlags(fs, args, "onboard",
		"Render docs/ONBOARDING.md for a registered repo. Idempotent.",
		[]flagDoc{
			{Name: "--refresh", Desc: "regenerate even if file already exists"},
			{Name: "--help, -h", Desc: "show this help and exit"},
		},
		[]string{"force onboard backend", "force onboard backend --refresh"})
	if helped {
		return
	}
	if perr != nil {
		os.Exit(2)
	}
	refresh := *refreshFlag
	positional := fs.Args()
	if len(positional) == 0 {
		fmt.Fprintln(os.Stderr, "onboard: <repo-spec> is required")
		printOnboardHelp()
		os.Exit(2)
	}
	if len(positional) > 1 {
		fmt.Fprintf(os.Stderr, "onboard: too many positional args (got %d, want 1)\n", len(positional))
		os.Exit(2)
	}
	repoSpec := positional[0]

	lib := librarian.NewInProcess(db)
	rendered, outPath, err := runOnboarding(ctx, db, lib, repoSpec)
	if err != nil {
		fmt.Fprintf(os.Stderr, "onboard: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, []byte(rendered), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "onboard: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	if refresh {
		fmt.Printf("onboard: refreshed %s (%d bytes)\n", outPath, len(rendered))
	} else {
		fmt.Printf("onboard: wrote %s (%d bytes)\n", outPath, len(rendered))
	}
}

// runOnboarding is the testable seam — pulls the digest via the
// librarian Client and renders to Markdown. Returns the rendered
// content and the absolute path it should be written to.
//
// The function does NOT touch disk for writes; the CLI handler does.
// Tests call runOnboarding directly to assert on the rendered shape
// without needing to manage temp-file ONBOARDING.md residue.
func runOnboarding(ctx context.Context, db *sql.DB, lib librarian.Client, repoSpec string) (string, string, error) {
	digest, err := lib.BuildRepoDigest(ctx, repoSpec)
	if err != nil {
		return "", "", fmt.Errorf("BuildRepoDigest(%s): %w", repoSpec, err)
	}
	if digest.LocalPath == "" {
		return "", "", fmt.Errorf("BuildRepoDigest(%s): empty LocalPath", repoSpec)
	}
	outPath := filepath.Join(digest.LocalPath, "ONBOARDING.md")
	displayName := digest.RepoName
	if displayName == "" {
		displayName = filepath.Base(digest.LocalPath)
	}
	rendered := renderOnboardingMarkdown(digest, displayName)
	_ = db // reserved for future per-repo audit-row writes; quiets unused-arg lint
	return rendered, outPath, nil
}

// renderOnboardingMarkdown shapes a librarian.RepoDigest into the
// 6-section Markdown structure mandated by D6 exit criterion #2.
//
// The function is pure — given the same digest it returns the same
// bytes (modulo the GeneratedAt timestamp the digest itself carries,
// which is propagated verbatim into the AUTO-GENERATED header).
//
// Sections (in order):
//
//  1. AUTO-GENERATED header
//  2. Title line
//  3. ## What this repo does
//  4. ## Public API surface
//  5. ## Key modules
//  6. ## Recent activity
//  7. ## Known fragility areas
//  8. ## Common conventions
func renderOnboardingMarkdown(digest librarian.RepoDigest, displayName string) string {
	var b strings.Builder
	// Header. Use the digest's GeneratedAt date (YYYY-MM-DD) so two
	// renders on the same UTC day produce identical headers — the
	// pre-commit drift check is byte-identical.
	dateOnly := digest.GeneratedAt
	if len(dateOnly) >= 10 {
		dateOnly = dateOnly[:10]
	} else if dateOnly == "" {
		dateOnly = time.Now().UTC().Format("2006-01-02")
	}
	fmt.Fprintf(&b, "%s %s` on %s; DO NOT HAND-EDIT. Regenerate with `force onboard --refresh %s`. -->\n\n",
		onboardingAutoGeneratedHeaderPrefix, displayName, dateOnly, displayName)
	fmt.Fprintf(&b, "# ONBOARDING — %s\n\n", displayName)

	// 1. What this repo does.
	b.WriteString("## What this repo does\n\n")
	b.WriteString(renderOnboardingWhatThisRepoDoes(digest))
	b.WriteString("\n")

	// 2. Public API surface.
	b.WriteString("## Public API surface\n\n")
	b.WriteString(renderOnboardingPublicAPI(digest))
	b.WriteString("\n")

	// 3. Key modules.
	b.WriteString("## Key modules\n\n")
	b.WriteString(renderOnboardingKeyModules(digest))
	b.WriteString("\n")

	// 4. Recent activity.
	b.WriteString("## Recent activity\n\n")
	b.WriteString(renderOnboardingRecentActivity(digest))
	b.WriteString("\n")

	// 5. Known fragility areas.
	b.WriteString("## Known fragility areas\n\n")
	b.WriteString(renderOnboardingFragility(digest))
	b.WriteString("\n")

	// 6. Common conventions.
	b.WriteString("## Common conventions\n\n")
	b.WriteString(renderOnboardingConventions(digest))

	return b.String()
}

// renderOnboardingWhatThisRepoDoes synthesises a 1-paragraph view of
// what the repo does from the registered description + the README's
// first non-blank paragraph + the top-level package list.
func renderOnboardingWhatThisRepoDoes(d librarian.RepoDigest) string {
	var parts []string
	if strings.TrimSpace(d.Description) != "" {
		parts = append(parts, strings.TrimSpace(d.Description)+".")
	}
	if first := firstReadmeParagraph(d.READMESample); first != "" {
		parts = append(parts, first)
	}
	if len(d.TopLevelDirs) > 0 {
		parts = append(parts, fmt.Sprintf("Top-level packages: %s.", strings.Join(d.TopLevelDirs, ", ")))
	}
	if len(parts) == 0 {
		return "_No README, registered description, or top-level packages detected. The repo may be brand-new or sparse._\n"
	}
	return strings.Join(parts, " ") + "\n"
}

// firstReadmeParagraph returns the first non-blank, non-heading
// paragraph from the README sample. Heuristic: skip leading blank +
// heading lines, then take everything up to the next blank line.
func firstReadmeParagraph(readme string) string {
	lines := strings.Split(readme, "\n")
	var collected []string
	started := false
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if !started {
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			started = true
			collected = append(collected, trimmed)
			continue
		}
		if trimmed == "" {
			break
		}
		collected = append(collected, trimmed)
	}
	if len(collected) == 0 {
		return ""
	}
	return strings.Join(collected, " ")
}

// renderOnboardingPublicAPI renders the detected interfaces / HTTP
// routes / CLI subcommands as bullet lists grouped by Kind. The
// digest already sorted them deterministically.
func renderOnboardingPublicAPI(d librarian.RepoDigest) string {
	if len(d.PublicAPISymbols) == 0 {
		return "_No exported interfaces, HTTP routes, or CLI subcommands detected by the lightweight regex scan. (The scan is best-effort — if you expect symbols here, the repo may not be Go, or its surfaces may use patterns the scanner doesn't yet match.)_\n"
	}
	groups := map[string][]librarian.APISymbol{}
	for _, sym := range d.PublicAPISymbols {
		groups[sym.Kind] = append(groups[sym.Kind], sym)
	}
	var b strings.Builder
	emit := func(label, kind string) {
		entries, ok := groups[kind]
		if !ok || len(entries) == 0 {
			return
		}
		fmt.Fprintf(&b, "**%s** (%d found):\n\n", label, len(entries))
		for _, e := range entries {
			fmt.Fprintf(&b, "- `%s` — %s\n", e.Name, e.Description)
		}
		b.WriteString("\n")
	}
	emit("Exported interfaces", "interface")
	emit("HTTP routes", "http")
	emit("CLI subcommands", "cli")
	return b.String()
}

// renderOnboardingKeyModules renders one bullet per top-level
// directory. We don't have package-level docs (this is regex-only),
// so the description is "<dir-name> — see <dir>/" and the renderer
// hints at where to look. A future iteration could read each
// directory's first .go file's package comment.
func renderOnboardingKeyModules(d librarian.RepoDigest) string {
	if len(d.TopLevelDirs) == 0 {
		return "_No top-level directories detected._\n"
	}
	var b strings.Builder
	for _, dir := range d.TopLevelDirs {
		fmt.Fprintf(&b, "- **`%s/`** — top-level package; inspect `%s/` for module-specific entry points and tests.\n", dir, dir)
	}
	return b.String()
}

// renderOnboardingRecentActivity summarises the recent-commits
// digest. We surface count, top contributors, and the 5 newest
// commit subjects — enough for an operator to sense the repo's
// pace without scrolling the full log.
func renderOnboardingRecentActivity(d librarian.RepoDigest) string {
	commits := d.RecentCommits.Commits
	if len(commits) == 0 {
		return "_No commits in the last 90 days, or the repo is not a registered git clone._\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "**%d commits** in the last 90 days", len(commits))
	if d.RecentCommits.Truncated {
		b.WriteString(" (digest truncated at the per-call cap)")
	}
	b.WriteString(".\n\n")

	// Top authors.
	authorCounts := map[string]int{}
	for _, c := range commits {
		authorCounts[c.Author]++
	}
	type kv struct {
		k string
		v int
	}
	var sorted []kv
	for k, v := range authorCounts {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].v != sorted[j].v {
			return sorted[i].v > sorted[j].v
		}
		return sorted[i].k < sorted[j].k
	})
	if len(sorted) > 0 {
		b.WriteString("**Top contributors:** ")
		var pieces []string
		max := 5
		if len(sorted) < max {
			max = len(sorted)
		}
		for i := 0; i < max; i++ {
			pieces = append(pieces, fmt.Sprintf("%s (%d)", sorted[i].k, sorted[i].v))
		}
		b.WriteString(strings.Join(pieces, ", "))
		b.WriteString("\n\n")
	}

	// Latest 5 subjects.
	b.WriteString("**Latest commits:**\n\n")
	max := 5
	if len(commits) < max {
		max = len(commits)
	}
	for i := 0; i < max; i++ {
		c := commits[i]
		short := c.SHA
		if len(short) > 7 {
			short = short[:7]
		}
		fmt.Fprintf(&b, "- `%s` — %s _(%s)_\n", short, c.Subject, c.Author)
	}
	return b.String()
}

// renderOnboardingFragility summarises FleetMemory failure-outcome
// rows scoped to the repo. For repos with no fleet activity (the
// usual case for a fresh-onboard target), emit the explicit
// "no fleet activity yet" string the spec mandates.
func renderOnboardingFragility(d librarian.RepoDigest) string {
	if d.RepoName == "" {
		return "_Repo is not registered with the orchestrator; no fleet activity yet._\n"
	}
	if len(d.FragilityMemories) == 0 {
		return "_No fleet activity yet — once tasks land in this repo, rejection patterns will surface here._\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "Aggregated rejection / failure summaries from the last %d failure-outcome FleetMemory rows:\n\n", len(d.FragilityMemories))
	for _, m := range d.FragilityMemories {
		summary := strings.TrimSpace(m.Summary)
		if summary == "" {
			summary = "_(no summary recorded)_"
		}
		fmt.Fprintf(&b, "- task #%d — %s\n", m.ParentTaskID, summary)
	}
	return b.String()
}

// renderOnboardingConventions surfaces the conventions files the
// digest pulled. Empty entries are skipped; non-empty entries are
// emitted as collapsed "<details>" blocks so the rendered Markdown
// stays scannable.
func renderOnboardingConventions(d librarian.RepoDigest) string {
	// Stable iteration order — the digest's map is unordered but the
	// list of names is deterministic.
	names := []string{"CLAUDE.md", "CONTRIBUTING.md", "SENATE.md"}
	var any bool
	var b strings.Builder
	for _, name := range names {
		body, ok := d.Conventions[name]
		if !ok || strings.TrimSpace(body) == "" {
			continue
		}
		any = true
		fmt.Fprintf(&b, "<details><summary><strong>%s</strong> (first 4 KB)</summary>\n\n", name)
		b.WriteString("```\n")
		b.WriteString(strings.TrimRight(body, "\n"))
		b.WriteString("\n```\n\n</details>\n\n")
	}
	if !any {
		return "_No CLAUDE.md, CONTRIBUTING.md, or SENATE.md found at the repo root._\n"
	}
	return b.String()
}

// printOnboardHelp renders the help text. Invoked from `force onboard --help`.
func printOnboardHelp() {
	fmt.Println(`Usage: force onboard <repo-spec> [--refresh]

  Synthetic onboarding doc generator. Reads a repo (registered or on-disk)
  and writes ONBOARDING.md at its root with these 6 sections:

    1. What this repo does
    2. Public API surface
    3. Key modules
    4. Recent activity
    5. Known fragility areas
    6. Common conventions

Args:
  <repo-spec>     Either a repo name registered with 'force add-repo'
                  OR a path to a directory on disk.
  --refresh       Same as a bare re-run; explicit "I want to refresh"
                  signal for cron / scripted invocations.

Anti-cheat:
  ONBOARDING.md is auto-generated. Hand-edits are rejected by the
  pre-commit hook (scripts/pre-commit/onboarding-md-check.sh).
  Re-run 'force onboard <repo>' to regenerate.`)
}

