package main

// onboard_test.go — D6 unit tests for the `force onboard` CLI.
//
// Coverage:
//
//   - TestOnboardingSynthesizesFromSenatorPipeline (exit criterion #4)
//     — the CLI invokes the same internal function the SenatorOnboarding
//       task uses. We assert this two ways, belt-and-suspenders:
//         (a) AST walk over inprocess_d4.go (the SenatorOnboarding
//             implementation) AND cmd/force/onboard.go: both must
//             reference the BuildRepoDigest selector.
//         (b) Behavioural — runOnboarding, given a mock librarian.Client,
//             must call MockClient.BuildRepoDigest exactly once.
//
//   - TestOnboardRendersSixRequiredSections (exit criterion #2) —
//     a rendered ONBOARDING.md has the 6 mandated section headings and
//     the AUTO-GENERATED header.
//
//   - TestOnboardWritesToRepoRoot — file lands at <local-path>/ONBOARDING.md.
//
//   - TestOnboardOnUnregisteredPath — disk-only repo path resolution works.
//
//   - TestOnboardRefreshFlagIsAlias — --refresh produces the same content
//     as a bare re-run (idempotence).
//
//   - TestOnboardHelpListsSubcommand (exit criterion #1) — `force onboard
//     --help` produces non-empty output mentioning the subcommand.

import (
	"context"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"force-orchestrator/internal/clients/librarian"
	"force-orchestrator/internal/store"
)

// TestOnboardingSynthesizesFromSenatorPipeline is exit criterion #4
// from the D6 spec — assert the CLI invokes the SAME internal function
// the SenatorOnboarding task uses.
//
// Two assertions:
//
//   (a) AST walk: both inprocess_d4.go (Senator path) AND onboard.go
//       (CLI path) reference the BuildRepoDigest selector. If either
//       file stops calling BuildRepoDigest, the test fails.
//
//   (b) Behavioural: runOnboarding, given a MockClient, calls exactly
//       BuildRepoDigest (recorded in MockClient.BuildDigestCalls).
func TestOnboardingSynthesizesFromSenatorPipeline(t *testing.T) {
	t.Run("AST_BothPathsCallBuildRepoDigest", func(t *testing.T) {
		repoRoot := repoRootForTest(t)
		paths := map[string]string{
			"senator-onboarding-task": filepath.Join(repoRoot, "internal", "clients", "librarian", "inprocess_d4.go"),
			"onboard-cli":             filepath.Join(repoRoot, "cmd", "force", "onboard.go"),
		}
		for label, path := range paths {
			if !fileMentionsSelector(t, path, "BuildRepoDigest") {
				t.Errorf("D6 anti-cheat: %s (%s) does NOT reference BuildRepoDigest. The CLI and the SenatorOnboarding task MUST share the digest assembly seam.", label, path)
			}
		}
	})

	t.Run("Behavioural_CLICallsBuildRepoDigestExactlyOnce", func(t *testing.T) {
		// Build a temp git repo so BuildRepoDigest can succeed against
		// it; we want the CLI's runOnboarding path to run end-to-end
		// against a mock librarian.Client whose BuildRepoDigest is
		// recorded.
		repoDir := newTempGitRepo(t, "TestOnboard\n")
		mock := librarian.NewMock()
		// Have the mock return a minimally-shaped digest so the
		// renderer doesn't crash on nil fields. The behavioural
		// assertion below is on the call recording, not the content.
		mock.BuildRepoDigestFn = func(ctx context.Context, repoSpec string) (librarian.RepoDigest, error) {
			return librarian.RepoDigest{
				LocalPath:   repoDir,
				Conventions: map[string]string{},
				GeneratedAt: "2026-05-02 00:00:00",
			}, nil
		}

		db := store.InitHolocronDSN(":memory:")
		defer db.Close()

		_, _, err := runOnboarding(context.Background(), db, mock, repoDir)
		if err != nil {
			t.Fatalf("runOnboarding: %v", err)
		}
		if got := len(mock.BuildDigestCalls); got != 1 {
			t.Fatalf("expected exactly 1 call to BuildRepoDigest, got %d (calls=%v)", got, mock.BuildDigestCalls)
		}
	})
}

// TestOnboardRendersSixRequiredSections checks exit criterion #2.
// A rendered ONBOARDING.md MUST carry:
//
//   - the AUTO-GENERATED header on its first line
//   - the title "# ONBOARDING — <repo>"
//   - all 6 ## section headings in order
func TestOnboardRendersSixRequiredSections(t *testing.T) {
	digest := librarian.RepoDigest{
		RepoName:    "fixture-repo",
		LocalPath:   "/tmp/fixture-repo",
		Description: "fixture for D6 rendering test",
		Conventions: map[string]string{},
		GeneratedAt: "2026-05-02 12:00:00",
	}
	out := renderOnboardingMarkdown(digest, digest.RepoName)

	// Header.
	firstLine := strings.SplitN(out, "\n", 2)[0]
	if !strings.HasPrefix(firstLine, onboardingAutoGeneratedHeaderPrefix) {
		t.Errorf("first line missing AUTO-GENERATED prefix; got %q", firstLine)
	}
	if !strings.Contains(firstLine, "DO NOT HAND-EDIT") {
		t.Errorf("AUTO-GENERATED header missing DO-NOT-HAND-EDIT clause; got %q", firstLine)
	}

	// Title.
	if !strings.Contains(out, "# ONBOARDING — fixture-repo") {
		t.Errorf("output missing title `# ONBOARDING — fixture-repo`")
	}

	// 6 sections, in order.
	wantSections := []string{
		"## What this repo does",
		"## Public API surface",
		"## Key modules",
		"## Recent activity",
		"## Known fragility areas",
		"## Common conventions",
	}
	idx := 0
	for _, section := range wantSections {
		pos := strings.Index(out[idx:], section)
		if pos < 0 {
			t.Errorf("rendered output missing section %q (or out of order at offset %d)", section, idx)
			continue
		}
		idx += pos + len(section)
	}
}

// TestOnboardWritesToRepoRoot covers the file-write path: the CLI lands
// ONBOARDING.md at the repo's local-path root.
func TestOnboardWritesToRepoRoot(t *testing.T) {
	repoDir := newTempGitRepo(t, "fixture\n")
	mock := librarian.NewMock()
	mock.BuildRepoDigestFn = func(ctx context.Context, repoSpec string) (librarian.RepoDigest, error) {
		return librarian.RepoDigest{
			RepoName:    "fixture",
			LocalPath:   repoDir,
			Conventions: map[string]string{},
			GeneratedAt: "2026-05-02 00:00:00",
		}, nil
	}
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	rendered, outPath, err := runOnboarding(context.Background(), db, mock, "fixture")
	if err != nil {
		t.Fatalf("runOnboarding: %v", err)
	}
	if outPath != filepath.Join(repoDir, "ONBOARDING.md") {
		t.Errorf("expected outPath=%s, got %s", filepath.Join(repoDir, "ONBOARDING.md"), outPath)
	}
	if !strings.HasPrefix(rendered, onboardingAutoGeneratedHeaderPrefix) {
		t.Errorf("rendered output missing AUTO-GENERATED prefix")
	}
}

// TestOnboardOnUnregisteredPath asserts the CLI handles the
// disk-path branch — repoSpec is an absolute directory path that is
// NOT registered.
func TestOnboardOnUnregisteredPath(t *testing.T) {
	repoDir := newTempGitRepo(t, "disk-only\n")
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()
	lib := librarian.NewInProcess(db)

	rendered, outPath, err := runOnboarding(context.Background(), db, lib, repoDir)
	if err != nil {
		t.Fatalf("runOnboarding: %v", err)
	}
	if !strings.HasPrefix(outPath, repoDir) {
		t.Errorf("expected outPath under %s, got %s", repoDir, outPath)
	}
	// The display name falls back to the directory's basename when
	// the repo isn't registered — assert that's how the title reads.
	wantTitle := "# ONBOARDING — " + filepath.Base(repoDir)
	if !strings.Contains(rendered, wantTitle) {
		t.Errorf("expected title %q in rendered output; got first 200 chars: %q", wantTitle, rendered[:min(200, len(rendered))])
	}
}

// TestOnboardRefreshFlagIsAlias asserts that --refresh produces the
// SAME content as a bare re-run. The flag is intentionally a behaviour
// alias (signal-of-intent only); a render that produced different
// bytes between the two would defeat that.
func TestOnboardRefreshFlagIsAlias(t *testing.T) {
	repoDir := newTempGitRepo(t, "refresh-equiv\n")
	mock := librarian.NewMock()
	fixedTimestamp := "2026-05-02 09:00:00"
	mock.BuildRepoDigestFn = func(ctx context.Context, repoSpec string) (librarian.RepoDigest, error) {
		return librarian.RepoDigest{
			RepoName:    "refresh-equiv",
			LocalPath:   repoDir,
			Conventions: map[string]string{},
			GeneratedAt: fixedTimestamp,
		}, nil
	}
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	first, _, err := runOnboarding(context.Background(), db, mock, "refresh-equiv")
	if err != nil {
		t.Fatalf("first runOnboarding: %v", err)
	}
	second, _, err := runOnboarding(context.Background(), db, mock, "refresh-equiv")
	if err != nil {
		t.Fatalf("second runOnboarding: %v", err)
	}
	if first != second {
		t.Errorf("runOnboarding is not deterministic: first run differs from second.\nFirst (truncated):\n%s\nSecond (truncated):\n%s",
			first[:min(400, len(first))], second[:min(400, len(second))])
	}
}

// TestOnboardHelpListsSubcommand covers exit criterion #1 — the
// `--help` invocation prints help text mentioning the subcommand.
// We exercise printOnboardHelp directly to avoid depending on
// os.Exit semantics.
func TestOnboardHelpListsSubcommand(t *testing.T) {
	out := captureOutput(printOnboardHelp)
	for _, want := range []string{
		"Usage: force onboard <repo-spec>",
		"What this repo does",
		"Public API surface",
		"Key modules",
		"Recent activity",
		"Known fragility areas",
		"Common conventions",
		"--refresh",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("printOnboardHelp output missing expected snippet %q\nfull output:\n%s", want, out)
		}
	}
}

// TestOnboardErrorOnMissingRepo asserts the CLI surfaces an error for
// a nonexistent repo / path (failure mode required by the project's
// "tests exercise real flows" rule).
func TestOnboardErrorOnMissingRepo(t *testing.T) {
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()
	lib := librarian.NewInProcess(db)
	_, _, err := runOnboarding(context.Background(), db, lib, "/nonexistent-repo-path-d6-test")
	if err == nil {
		t.Fatalf("expected error for missing repo, got nil")
	}
	if !strings.Contains(err.Error(), "neither a registered repo nor a directory") {
		t.Errorf("error message should explain the resolution failure; got %v", err)
	}
}

// ── helpers ──────────────────────────────────────────────────────────

func fileMentionsSelector(t *testing.T, path, selector string) bool {
	t.Helper()
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	found := false
	ast.Inspect(f, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if sel.Sel != nil && sel.Sel.Name == selector {
			found = true
			return false
		}
		return true
	})
	return found
}

func repoRootForTest(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("runtime.Caller failed")
	}
	// onboard_test.go is at <root>/cmd/force/onboard_test.go
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

func newTempGitRepo(t *testing.T, readmeBody string) string {
	t.Helper()
	dir := t.TempDir()
	mustRunGitForOnboardTest(t, dir, "init", "-q")
	mustRunGitForOnboardTest(t, dir, "config", "user.email", "test@example.com")
	mustRunGitForOnboardTest(t, dir, "config", "user.name", "Test")
	mustRunGitForOnboardTest(t, dir, "config", "commit.gpgsign", "false")
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(readmeBody), 0644); err != nil {
		t.Fatalf("write README.md: %v", err)
	}
	mustRunGitForOnboardTest(t, dir, "add", "README.md")
	mustRunGitForOnboardTest(t, dir, "commit", "-q", "-m", "seed")
	return dir
}

func mustRunGitForOnboardTest(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME=t", "GIT_AUTHOR_EMAIL=t@x",
		"GIT_COMMITTER_NAME=t", "GIT_COMMITTER_EMAIL=t@x",
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v — %s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
}
