// D3 P6A.7 — Pattern P28: NarrativeRenders is generated by exactly one
// site, the prompt template is in code (not the DB), and the prompt
// version stamp matches the const.
package audittools

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPattern_P28_NarrativeIsGenerated(t *testing.T) {
	root := repoRootP28(t)

	// 1. Exactly one production file inserts into NarrativeRenders.
	matches := grepInsertNarrativeRenders(t, root)
	if len(matches) != 1 {
		t.Errorf("Pattern P28 violation: NarrativeRenders inserted from %d files; want exactly 1 (narrative_renderer.go).\nFiles: %s",
			len(matches), strings.Join(matches, ", "))
	}
	if len(matches) == 1 && !strings.HasSuffix(matches[0], "narrative_renderer.go") {
		t.Errorf("Pattern P28: NarrativeRenders insert is in %q, want narrative_renderer.go", matches[0])
	}

	// 2. The prompt template lives in code under
	// internal/agents/narrative_prompts/.
	promptDir := filepath.Join(root, "internal/agents/narrative_prompts")
	if _, err := os.Stat(promptDir); err != nil {
		t.Errorf("Pattern P28: narrative_prompts/ directory missing")
	}
	v1, err := os.ReadFile(filepath.Join(promptDir, "v1.go"))
	if err != nil {
		t.Errorf("Pattern P28: narrative_prompts/v1.go missing: %v", err)
		return
	}
	if !strings.Contains(string(v1), "PromptVersion") {
		t.Errorf("Pattern P28: PromptVersion const missing from narrative_prompts/v1.go")
	}
	if !strings.Contains(string(v1), "PromptTemplate") {
		t.Errorf("Pattern P28: PromptTemplate const missing from narrative_prompts/v1.go")
	}
}

func grepInsertNarrativeRenders(t *testing.T, root string) []string {
	t.Helper()
	var hits []string
	dirs := []string{"internal/agents", "internal/dashboard", "internal/store"}
	for _, dir := range dirs {
		_ = filepath.Walk(filepath.Join(root, dir), func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			src, _ := os.ReadFile(path)
			text := string(src)
			if strings.Contains(text, "INSERT INTO NarrativeRenders") {
				rel, _ := filepath.Rel(root, path)
				hits = append(hits, filepath.ToSlash(rel))
			}
			return nil
		})
	}
	return hits
}

func repoRootP28(t *testing.T) string {
	t.Helper()
	wd, _ := os.Getwd()
	for d := wd; d != "/" && d != ""; d = filepath.Dir(d) {
		if _, err := os.Stat(filepath.Join(d, "go.mod")); err == nil {
			return d
		}
	}
	t.Fatalf("repo root not found from %s", wd)
	return ""
}
