package agents

// D10 — dogArchitectureDocRender tests.
//
// Coverage:
//   - Default-OFF: a fresh repo (handoff_synthesis_enabled=0) does NOT
//     trigger the renderer; ARCHITECTURE.md is not written.
//   - Flag-on: an enabled repo gets ARCHITECTURE.md written with the
//     AUTO-GENERATED header at <repo>/ARCHITECTURE.md.
//   - Idempotent re-run: a second tick produces the same body.
//   - Renderer regression guard: a librarian that returns a body
//     missing the AUTO-GENERATED header is rejected (no file written).

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"force-orchestrator/internal/clients/librarian"
	"force-orchestrator/internal/store"
)

// TestDogArchitectureDocRender_DefaultOffSkipsAllRepos asserts the
// dog short-circuits when no repo is enabled — the renderer is not
// called and no file is written.
func TestDogArchitectureDocRender_DefaultOffSkipsAllRepos(t *testing.T) {
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	repoDir := t.TempDir()
	store.AddRepo(db, "off-repo", repoDir, "test")
	// Default flag is 0 — no SetHandoffSynthesisEnabled call.

	mock := librarian.NewMock()
	if err := dogArchitectureDocRender(context.Background(), db, mock, testLogger{}); err != nil {
		t.Fatalf("dogArchitectureDocRender: %v", err)
	}
	if got := len(mock.BuildArchitectureCalls); got != 0 {
		t.Errorf("expected 0 BuildArchitectureDoc calls when flag is off; got %d (%v)",
			got, mock.BuildArchitectureCalls)
	}
	if _, err := os.Stat(filepath.Join(repoDir, "ARCHITECTURE.md")); err == nil {
		t.Errorf("ARCHITECTURE.md was written when flag is off — anti-cheat violation")
	} else if !os.IsNotExist(err) {
		t.Errorf("unexpected stat err: %v", err)
	}
}

// TestDogArchitectureDocRender_EnabledRepoEmitsFile covers the
// happy path: an enrolled repo gets ARCHITECTURE.md written with
// the AUTO-GENERATED header line.
func TestDogArchitectureDocRender_EnabledRepoEmitsFile(t *testing.T) {
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	repoDir := t.TempDir()
	store.AddRepo(db, "on-repo", repoDir, "test")
	if err := store.SetHandoffSynthesisEnabled(db, "on-repo", true); err != nil {
		t.Fatalf("SetHandoffSynthesisEnabled: %v", err)
	}

	mock := librarian.NewMock()
	mock.BuildArchitectureDocFn = func(_ context.Context, repoSpec string) (librarian.ArchitectureDoc, error) {
		return librarian.ArchitectureDoc{
			RepoName:    repoSpec,
			LocalPath:   repoDir,
			Markdown:    "<!-- AUTO-GENERATED by `dogArchitectureDocRender` on 2026-05-02; DO NOT HAND-EDIT. -->\n\n# ARCHITECTURE — on-repo\n\nBody.\n",
			GeneratedAt: "2026-05-02 00:00:00",
		}, nil
	}

	if err := dogArchitectureDocRender(context.Background(), db, mock, testLogger{}); err != nil {
		t.Fatalf("dogArchitectureDocRender: %v", err)
	}
	if got := len(mock.BuildArchitectureCalls); got != 1 {
		t.Errorf("expected 1 BuildArchitectureDoc call; got %d", got)
	}

	body, err := os.ReadFile(filepath.Join(repoDir, "ARCHITECTURE.md"))
	if err != nil {
		t.Fatalf("ARCHITECTURE.md not written: %v", err)
	}
	if !strings.HasPrefix(string(body), architectureDocAutoGeneratedHeaderPrefix) {
		end := 80
		if end > len(body) {
			end = len(body)
		}
		t.Errorf("ARCHITECTURE.md does not start with the AUTO-GENERATED prefix; first 80 bytes=%q",
			string(body[:end]))
	}
}

// TestDogArchitectureDocRender_RejectsBodyMissingHeader is the
// renderer-regression guard: a buggy renderer that drops the header
// must NOT result in a written file (otherwise the pre-commit hook
// would later reject every commit and the operator would have a
// confusing time tracking down the cause).
func TestDogArchitectureDocRender_RejectsBodyMissingHeader(t *testing.T) {
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	repoDir := t.TempDir()
	store.AddRepo(db, "no-header-repo", repoDir, "test")
	if err := store.SetHandoffSynthesisEnabled(db, "no-header-repo", true); err != nil {
		t.Fatalf("SetHandoffSynthesisEnabled: %v", err)
	}

	mock := librarian.NewMock()
	mock.BuildArchitectureDocFn = func(_ context.Context, repoSpec string) (librarian.ArchitectureDoc, error) {
		return librarian.ArchitectureDoc{
			RepoName:  repoSpec,
			LocalPath: repoDir,
			Markdown:  "# ARCHITECTURE — header dropped by buggy renderer\n",
		}, nil
	}

	err := dogArchitectureDocRender(context.Background(), db, mock, testLogger{})
	if err == nil {
		t.Errorf("expected dogArchitectureDocRender to return an error when renderer drops the AUTO-GENERATED header; got nil")
	}
	if _, statErr := os.Stat(filepath.Join(repoDir, "ARCHITECTURE.md")); statErr == nil {
		t.Errorf("ARCHITECTURE.md was written despite missing header — invariant violated")
	} else if !os.IsNotExist(statErr) {
		t.Errorf("unexpected stat err: %v", statErr)
	}
}

// TestDogArchitectureDocRender_PropagatesLibrarianError exercises
// errors.Join aggregation: one repo errors, another succeeds, the
// dog reports both outcomes.
func TestDogArchitectureDocRender_PropagatesLibrarianError(t *testing.T) {
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	repoDirA := t.TempDir()
	store.AddRepo(db, "ok-repo", repoDirA, "test")
	if err := store.SetHandoffSynthesisEnabled(db, "ok-repo", true); err != nil {
		t.Fatalf("SetHandoffSynthesisEnabled(ok): %v", err)
	}
	repoDirB := t.TempDir()
	store.AddRepo(db, "err-repo", repoDirB, "test")
	if err := store.SetHandoffSynthesisEnabled(db, "err-repo", true); err != nil {
		t.Fatalf("SetHandoffSynthesisEnabled(err): %v", err)
	}

	mock := librarian.NewMock()
	mock.BuildArchitectureDocFn = func(_ context.Context, repoSpec string) (librarian.ArchitectureDoc, error) {
		if repoSpec == "err-repo" {
			return librarian.ArchitectureDoc{}, errors.New("synthetic librarian failure")
		}
		dir := repoDirA
		return librarian.ArchitectureDoc{
			RepoName:  repoSpec,
			LocalPath: dir,
			Markdown:  "<!-- AUTO-GENERATED by `dogArchitectureDocRender` on 2026-05-02; DO NOT HAND-EDIT. -->\n\n# ARCHITECTURE — ok-repo\n\nBody.\n",
		}, nil
	}

	err := dogArchitectureDocRender(context.Background(), db, mock, testLogger{})
	if err == nil {
		t.Errorf("expected an aggregated error from the failing repo; got nil")
	}
	if !strings.Contains(err.Error(), "synthetic librarian failure") {
		t.Errorf("expected aggregated error to mention the synthetic failure; got %v", err)
	}
	// ok-repo still got its file.
	if _, statErr := os.Stat(filepath.Join(repoDirA, "ARCHITECTURE.md")); statErr != nil {
		t.Errorf("ok-repo ARCHITECTURE.md missing despite successful render: %v", statErr)
	}
}

// TestDogArchitectureDocRender_NilLibrarianClientNoOps mirrors the
// SUPPLY dog's nil-handler behaviour: a daemon that couldn't
// construct an in-process librarian client should see this dog
// silently skip rather than panic.
func TestDogArchitectureDocRender_NilLibrarianClientNoOps(t *testing.T) {
	db := store.InitHolocronDSN(":memory:")
	defer db.Close()

	repoDir := t.TempDir()
	store.AddRepo(db, "any-repo", repoDir, "test")
	if err := store.SetHandoffSynthesisEnabled(db, "any-repo", true); err != nil {
		t.Fatalf("SetHandoffSynthesisEnabled: %v", err)
	}

	if err := dogArchitectureDocRender(context.Background(), db, nil, testLogger{}); err != nil {
		t.Errorf("expected nil error on nil librarian client (skip path); got %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(repoDir, "ARCHITECTURE.md")); statErr == nil {
		t.Errorf("ARCHITECTURE.md was written despite nil librarian client")
	}
}

