package agents

// D10 — dogArchitectureDocRender.
//
// Triggered (logically) on every merge to main of an enabled repo
// (Repositories.handoff_synthesis_enabled=1). The dog's per-cycle
// shape walks every enabled repo and renders ARCHITECTURE.md via
// librarian.Client.BuildArchitectureDoc, writing the result to
// <repo-local-path>/ARCHITECTURE.md.
//
// Anti-cheat invariants enforced here:
//
//   - Default-OFF: only repos with handoff_synthesis_enabled=1 are
//     processed. The flag default is 0; tests assert a fresh repo
//     does NOT trigger the dog's render path.
//   - AUTO-GENERATED header: BuildArchitectureDoc stamps the header
//     and the dog refuses to write a body that doesn't carry it.
//     This prevents a renderer regression from silently producing
//     a hand-edit-look-alike.
//   - No CLAUDE.md duplication: enforced separately by
//     TestArchitectureMdNotDuplicateOfClaudeMd against synthetic
//     fixtures (see librarian/inprocess_d10_test.go).

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"force-orchestrator/internal/clients/librarian"
	"force-orchestrator/internal/store"
)

// architectureDocFilename is the on-disk filename written into each
// enabled repo. Mirrors ONBOARDING.md's "single canonical filename"
// shape so the pre-commit hook's basename match is unambiguous.
const architectureDocFilename = "ARCHITECTURE.md"

// architectureDocAutoGeneratedHeaderPrefix is the literal prefix the
// renderer stamps + the dog refuses to write a body without. Kept
// in sync with the renderer's
// `architectureDocAutoGeneratedHeaderPrefix` constant in the
// librarian package — duplicating the literal here is cheap and
// avoids a cross-package import for one short string.
const architectureDocAutoGeneratedHeaderPrefix = "<!-- AUTO-GENERATED by `dogArchitectureDocRender`"

// dogArchitectureDocRender walks every repo with
// handoff_synthesis_enabled=1 and re-renders <repo>/ARCHITECTURE.md.
// Errors per-repo are aggregated via errors.Join so a single repo's
// hiccup doesn't block the rest.
func dogArchitectureDocRender(ctx context.Context, db *sql.DB, lib librarian.Client, logger interface{ Printf(string, ...any) }) error {
	if lib == nil {
		// Mirrors dogSupplyAllowlistRefresh's nil-client treatment:
		// log + skip rather than panic. Operator-side fix is to
		// thread the in-process librarian through the daemon
		// constructor.
		logger.Printf("Dog architecture-doc-render: librarian client unavailable; skipping")
		return nil
	}

	repos := store.ListRepos(db)
	enabled := make([]store.Repository, 0, len(repos))
	for _, r := range repos {
		if !r.HandoffSynthesisEnabled {
			continue
		}
		if strings.TrimSpace(r.LocalPath) == "" {
			logger.Printf("Dog architecture-doc-render: repo %q is enabled but has no local_path; skipping", r.Name)
			continue
		}
		enabled = append(enabled, r)
	}

	if len(enabled) == 0 {
		logger.Printf("Dog architecture-doc-render: no repos with handoff_synthesis_enabled=1; nothing to render")
		return nil
	}

	var aggErr error
	rendered := 0
	skipped := 0
	for _, r := range enabled {
		if err := ctx.Err(); err != nil {
			aggErr = errors.Join(aggErr, fmt.Errorf("%s: %w", r.Name, err))
			break
		}
		written, err := renderArchitectureDocForRepo(ctx, lib, r.Name)
		if err != nil {
			aggErr = errors.Join(aggErr, fmt.Errorf("repo %s: %w", r.Name, err))
			continue
		}
		if written {
			rendered++
		} else {
			skipped++
		}
	}

	logger.Printf("Dog architecture-doc-render: enabled=%d rendered=%d skipped=%d",
		len(enabled), rendered, skipped)
	return aggErr
}

// renderArchitectureDocForRepo handles one (repo) render. Returns
// (true, nil) when ARCHITECTURE.md was written; (false, nil) when
// the renderer produced an empty body (defensive); (_, err) on any
// error path.
//
// Idempotence: writing the same bytes twice is a no-op for the
// pre-commit hook (the staged blob's first line still starts with
// the AUTO-GENERATED prefix), so this function is safe to call
// every dog tick.
func renderArchitectureDocForRepo(ctx context.Context, lib librarian.Client, repoSpec string) (bool, error) {
	doc, err := lib.BuildArchitectureDoc(ctx, repoSpec)
	if err != nil {
		return false, fmt.Errorf("BuildArchitectureDoc: %w", err)
	}
	if strings.TrimSpace(doc.Markdown) == "" {
		return false, nil
	}
	if !strings.HasPrefix(doc.Markdown, architectureDocAutoGeneratedHeaderPrefix) {
		return false, fmt.Errorf("renderer regression: ARCHITECTURE.md body does not start with the AUTO-GENERATED header (refusing to write %s)", repoSpec)
	}
	if doc.LocalPath == "" {
		return false, fmt.Errorf("BuildArchitectureDoc returned empty LocalPath for %s", repoSpec)
	}
	outPath := filepath.Join(doc.LocalPath, architectureDocFilename)
	if err := os.WriteFile(outPath, []byte(doc.Markdown), 0644); err != nil {
		return false, fmt.Errorf("write %s: %w", outPath, err)
	}
	return true, nil
}
