// dogs_arch_health_hook_test.go — D9 ArchHealth pre-commit hook tests.
//
// Exercises scripts/pre-commit/arch-health-md-check.sh against a real
// throwaway git repo:
//
//   - hand-edited reports/architecture-health-*.md (no AUTO-GENERATED
//     header) → hook exits 1.
//   - properly-headered reports/architecture-health-*.md → hook exits 0.
//   - no architecture-health files staged → hook exits 0.
//
// We locate the hook via runtime.Caller so the test works in either
// the parent worktree or a CI checkout.

package agents

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// resolveArchHealthHook walks up from this test file to find the
// scripts/pre-commit/arch-health-md-check.sh script.
func resolveArchHealthHook(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Skip("cannot determine test file path via runtime.Caller")
	}
	// thisFile is .../internal/agents/dogs_arch_health_hook_test.go
	root := filepath.Dir(filepath.Dir(filepath.Dir(thisFile)))
	hook := filepath.Join(root, "scripts", "pre-commit", "arch-health-md-check.sh")
	if _, err := os.Stat(hook); err != nil {
		t.Fatalf("hook not found at %s: %v", hook, err)
	}
	return hook
}

// initBareRepo runs `git init` in dir and configures committer info
// (required for `git commit` to succeed in CI sandboxes).
func initBareRepo(t *testing.T, dir string) {
	t.Helper()
	for _, args := range [][]string{
		{"init", "--quiet", "-b", "main"},
		{"config", "user.email", "test@example.com"},
		{"config", "user.name", "Test"},
	} {
		var cmd *exec.Cmd
		if args[0] == "init" {
			cmd = exec.Command("git", append(args, dir)...)
		} else {
			cmd = exec.Command("git", append([]string{"-C", dir}, args...)...)
		}
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
}

func gitInRepo(t *testing.T, dir string, args ...string) ([]byte, error) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	return cmd.CombinedOutput()
}

func runHook(t *testing.T, hook, repoDir string) (int, string) {
	t.Helper()
	cmd := exec.Command("bash", hook)
	cmd.Dir = repoDir
	out, err := cmd.CombinedOutput()
	exitCode := 0
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			exitCode = ee.ExitCode()
		} else {
			t.Fatalf("hook run failed (non-ExitError): %v\n%s", err, out)
		}
	}
	return exitCode, string(out)
}

// TestArchHealthHook_RejectsHandEdit — a staged
// reports/architecture-health-*.md without the AUTO-GENERATED header is
// rejected (exit 1).
func TestArchHealthHook_RejectsHandEdit(t *testing.T) {
	hook := resolveArchHealthHook(t)
	repo := t.TempDir()
	initBareRepo(t, repo)

	if err := os.MkdirAll(filepath.Join(repo, "reports"), 0o755); err != nil {
		t.Fatal(err)
	}
	// Hand-edited body — first line does NOT start with the
	// AUTO-GENERATED prefix.
	if err := os.WriteFile(filepath.Join(repo, "reports", "architecture-health-2026-05.md"),
		[]byte("# I edited this by hand\n\nthis should be rejected\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := gitInRepo(t, repo, "add", "reports/architecture-health-2026-05.md"); err != nil {
		t.Fatalf("git add: %v\n%s", err, out)
	}

	exitCode, out := runHook(t, hook, repo)
	if exitCode != 1 {
		t.Errorf("expected hook exit 1; got %d; output:\n%s", exitCode, out)
	}
	if !strings.Contains(out, "REJECT") {
		t.Errorf("expected REJECT message; got:\n%s", out)
	}
}

// TestArchHealthHook_AcceptsAutoGenerated — a properly-headered staged
// file passes the hook (exit 0).
func TestArchHealthHook_AcceptsAutoGenerated(t *testing.T) {
	hook := resolveArchHealthHook(t)
	repo := t.TempDir()
	initBareRepo(t, repo)

	if err := os.MkdirAll(filepath.Join(repo, "reports"), 0o755); err != nil {
		t.Fatal(err)
	}
	body := archHealthAutoGeneratedPrefix + " on 2026-05-01T00:00:00Z. -->\n\n# Architecture Health Report\n"
	if err := os.WriteFile(filepath.Join(repo, "reports", "architecture-health-2026-05.md"),
		[]byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := gitInRepo(t, repo, "add", "reports/architecture-health-2026-05.md"); err != nil {
		t.Fatalf("git add: %v\n%s", err, out)
	}

	exitCode, out := runHook(t, hook, repo)
	if exitCode != 0 {
		t.Errorf("expected hook exit 0; got %d; output:\n%s", exitCode, out)
	}
}

// TestArchHealthHook_NothingStaged — empty staging area: exit 0 (no
// hook applies).
func TestArchHealthHook_NothingStaged(t *testing.T) {
	hook := resolveArchHealthHook(t)
	repo := t.TempDir()
	initBareRepo(t, repo)

	exitCode, out := runHook(t, hook, repo)
	if exitCode != 0 {
		t.Errorf("expected hook exit 0 with nothing staged; got %d; output:\n%s", exitCode, out)
	}
}

// TestArchHealthHook_UnrelatedFileIgnored — a staged file that doesn't
// match reports/architecture-health-*.md must not trigger the hook.
func TestArchHealthHook_UnrelatedFileIgnored(t *testing.T) {
	hook := resolveArchHealthHook(t)
	repo := t.TempDir()
	initBareRepo(t, repo)

	if err := os.WriteFile(filepath.Join(repo, "README.md"), []byte("hello\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := gitInRepo(t, repo, "add", "README.md"); err != nil {
		t.Fatalf("git add: %v\n%s", err, out)
	}
	exitCode, out := runHook(t, hook, repo)
	if exitCode != 0 {
		t.Errorf("expected hook exit 0; got %d; output:\n%s", exitCode, out)
	}
}
