// dogs_arch_health_render.go — D9 ArchHealth renderer.
//
// renderArchHealthReport reads ArchHealthAggregates for the given month
// and writes a six-section Markdown report to
// reports/architecture-health-<month>.md. The report carries an
// AUTO-GENERATED header so the matching pre-commit hook
// (scripts/pre-commit/arch-health-md-check.sh) refuses hand-edits.
//
// Sections (per docs/roadmap.md § D9-ArchHealth):
//
//	1. Executive summary — total violations + per-repo invariant-health score.
//	2. Per-invariant — current count, MoM delta, 6-month trend (sparkline).
//	3. Per-repo — invariant-health score (weighted average; higher = healthier).
//	4. Per-author — compliance rate per author_type; flag if astromech worse than human.
//	5. 6-month trend — month × rule_id violation matrix.
//	6. Methodology — what the dog scanned, how author_type is classified, weights file.
//
// The renderer is pure I/O: it reads ArchHealthAggregates and the
// docs/arch-health-weights.yaml file, and writes one .md file. It does
// not mutate the DB.

package agents

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"force-orchestrator/internal/bos"
	"force-orchestrator/internal/store"
)

// archHealthAutoGeneratedPrefix is the exact opening string the renderer
// stamps at the top of every reports/architecture-health-*.md file.
// scripts/pre-commit/arch-health-md-check.sh greps for this prefix to
// distinguish renderer output from hand-edits. Keep these strings in
// lock-step.
const archHealthAutoGeneratedPrefix = "<!-- AUTO-GENERATED by `force dog architecture-health-report`"

// renderArchHealthReport reads the persisted aggregates for `month` and
// writes the .md report. Returns the path written.
func renderArchHealthReport(db *sql.DB, month string, repoNames map[int]string) (string, error) {
	aggs, err := store.ListArchHealthAggregatesForMonth(db, month)
	if err != nil {
		return "", fmt.Errorf("ListArchHealthAggregatesForMonth: %w", err)
	}

	// Load weights (best-effort — missing or unreadable file degrades to
	// all-1.0 weights with a "weights unavailable" footnote).
	weights, weightsErr := loadArchHealthWeights(archHealthWeightsPath)
	weightsLoaded := weightsErr == nil

	// Load every registered rule for the per-invariant section so a rule
	// with zero violations still appears (the report should show "100%
	// clean" rules, not silently omit them).
	allRules := bos.All()

	// 6-month trend uses the trailing 6 months ending at `month`.
	trendMonths := trailingSixMonths(month)

	var sb strings.Builder
	writeArchHealthHeader(&sb, month)
	writeArchHealthExecutiveSummary(&sb, aggs, repoNames, weights)
	writeArchHealthPerInvariantSection(db, &sb, aggs, allRules, trendMonths)
	writeArchHealthPerRepoSection(&sb, aggs, repoNames, weights)
	writeArchHealthPerAuthorSection(&sb, aggs)
	writeArchHealthTrendSection(db, &sb, trendMonths)
	writeArchHealthMethodology(&sb, weightsLoaded)

	if mkErr := os.MkdirAll(archHealthReportsDir, 0o755); mkErr != nil {
		return "", fmt.Errorf("mkdir %s: %w", archHealthReportsDir, mkErr)
	}
	path := filepath.Join(archHealthReportsDir, fmt.Sprintf("architecture-health-%s.md", month))
	if wErr := os.WriteFile(path, []byte(sb.String()), 0o644); wErr != nil {
		return "", fmt.Errorf("write %s: %w", path, wErr)
	}
	return path, nil
}

// writeArchHealthHeader writes the AUTO-GENERATED preamble. The first
// line is consumed by scripts/pre-commit/arch-health-md-check.sh.
func writeArchHealthHeader(sb *strings.Builder, month string) {
	now := archHealthClock()
	fmt.Fprintf(sb, "%s on %s. -->\n", archHealthAutoGeneratedPrefix, now.Format(time.RFC3339))
	fmt.Fprintf(sb, "<!-- DO NOT EDIT BY HAND. The matching pre-commit hook (scripts/pre-commit/arch-health-md-check.sh) rejects hand-edits. -->\n\n")
	fmt.Fprintf(sb, "# Architecture Health Report — %s\n\n", month)
	fmt.Fprintf(sb, "Generated by the `architecture-health-report` dog on %s.\n", now.Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(sb, "Per-rule weights: `docs/arch-health-weights.yaml`. Scope: every BoS rule × every registered repo, full current codebase.\n\n")
}

// writeArchHealthExecutiveSummary is section 1.
func writeArchHealthExecutiveSummary(sb *strings.Builder, aggs []store.ArchHealthAggregate, repoNames map[int]string, weights map[string]float64) {
	totalViolations := 0
	perRepoTotal := map[int]int{}
	for _, a := range aggs {
		totalViolations += a.ViolationCount
		perRepoTotal[a.RepoID] += a.ViolationCount
	}
	fmt.Fprintf(sb, "## 1. Executive Summary\n\n")
	fmt.Fprintf(sb, "- **Total violations**: %d\n", totalViolations)
	fmt.Fprintf(sb, "- **Repos scanned**: %d\n", len(repoNames))
	fmt.Fprintf(sb, "- **Distinct rules firing**: %d\n", distinctRules(aggs))
	fmt.Fprintf(sb, "\n")

	// Per-repo health score (higher = healthier; capped at 100).
	type repoScore struct {
		id    int
		name  string
		score float64
	}
	var rows []repoScore
	for id, name := range repoNames {
		score := computeRepoHealthScore(aggs, id, weights)
		rows = append(rows, repoScore{id: id, name: name, score: score})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].score > rows[j].score })
	fmt.Fprintf(sb, "| Repo | Health Score | Violations |\n")
	fmt.Fprintf(sb, "|---|---:|---:|\n")
	for _, r := range rows {
		fmt.Fprintf(sb, "| %s | %.1f | %d |\n", r.name, r.score, perRepoTotal[r.id])
	}
	fmt.Fprintf(sb, "\n")
}

// writeArchHealthPerInvariantSection is section 2 — per-rule current
// count, MoM delta, and a 6-month sparkline (ASCII bar chart).
func writeArchHealthPerInvariantSection(db *sql.DB, sb *strings.Builder, aggs []store.ArchHealthAggregate, allRules []bos.Rule, trendMonths []string) {
	fmt.Fprintf(sb, "## 2. Per-Invariant\n\n")
	fmt.Fprintf(sb, "| Rule | CLAUDE.md Anchor | This Month | MoM Δ | 6-Month Trend |\n")
	fmt.Fprintf(sb, "|---|---|---:|---:|---|\n")
	currentMonth := ""
	if len(trendMonths) > 0 {
		currentMonth = trendMonths[len(trendMonths)-1]
	}
	priorMonth := ""
	if len(trendMonths) >= 2 {
		priorMonth = trendMonths[len(trendMonths)-2]
	}

	currentByRule := map[string]int{}
	for _, a := range aggs {
		currentByRule[a.RuleID] += a.ViolationCount
	}

	priorByRule := map[string]int{}
	if priorMonth != "" {
		priorAggs, _ := store.ListArchHealthAggregatesForMonth(db, priorMonth)
		for _, a := range priorAggs {
			priorByRule[a.RuleID] += a.ViolationCount
		}
	}

	for _, r := range allRules {
		ruleID := r.ID()
		current := currentByRule[ruleID]
		prior := priorByRule[ruleID]
		delta := current - prior
		deltaStr := fmt.Sprintf("%+d", delta)
		if priorMonth == "" {
			deltaStr = "—"
		}
		spark := buildSparkline(db, ruleID, trendMonths)
		fmt.Fprintf(sb, "| %s | %s | %d | %s | %s |\n",
			ruleID, r.CLAUDEMDAnchor(), current, deltaStr, spark)
	}
	fmt.Fprintf(sb, "\n_This month: %s. Prior: %s._\n\n", currentMonth, ifEmpty(priorMonth, "(none)"))
}

// writeArchHealthPerRepoSection is section 3.
func writeArchHealthPerRepoSection(sb *strings.Builder, aggs []store.ArchHealthAggregate, repoNames map[int]string, weights map[string]float64) {
	fmt.Fprintf(sb, "## 3. Per-Repo\n\n")
	fmt.Fprintf(sb, "Per-repo invariant-health score (weighted average; higher = healthier; capped at 100).\n\n")
	fmt.Fprintf(sb, "| Repo | Health Score | Top Rule | Top Rule Count |\n")
	fmt.Fprintf(sb, "|---|---:|---|---:|\n")

	// Compute per (repo, rule) totals so we can pick the noisiest rule.
	type rk struct {
		repoID int
		ruleID string
	}
	tot := map[rk]int{}
	for _, a := range aggs {
		tot[rk{a.RepoID, a.RuleID}] += a.ViolationCount
	}
	var ids []int
	for id := range repoNames {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	for _, id := range ids {
		score := computeRepoHealthScore(aggs, id, weights)
		topRule := ""
		topCount := 0
		for k, v := range tot {
			if k.repoID != id {
				continue
			}
			if v > topCount {
				topCount = v
				topRule = k.ruleID
			}
		}
		if topRule == "" {
			topRule = "(clean)"
		}
		fmt.Fprintf(sb, "| %s | %.1f | %s | %d |\n", repoNames[id], score, topRule, topCount)
	}
	fmt.Fprintf(sb, "\n")
}

// writeArchHealthPerAuthorSection is section 4 — astromech-vs-human flag.
func writeArchHealthPerAuthorSection(sb *strings.Builder, aggs []store.ArchHealthAggregate) {
	fmt.Fprintf(sb, "## 4. Per-Author\n\n")
	totals := map[string]int{}
	for _, a := range aggs {
		totals[a.AuthorType] += a.ViolationCount
	}
	human := totals[archAuthorHuman]
	astromech := totals[archAuthorAstromech]
	archaeo := totals[archAuthorArchaeologistMigration]

	flag := ""
	if astromech > human {
		flag = " ⚠️ astromech violations exceed human; investigate astromech rule discipline."
	}

	fmt.Fprintf(sb, "| Author Type | Violations |\n")
	fmt.Fprintf(sb, "|---|---:|\n")
	fmt.Fprintf(sb, "| human | %d |\n", human)
	fmt.Fprintf(sb, "| astromech | %d |\n", astromech)
	fmt.Fprintf(sb, "| archaeologist-migration | %d |\n", archaeo)
	fmt.Fprintf(sb, "\n")
	if flag != "" {
		fmt.Fprintf(sb, "%s\n\n", flag)
	} else {
		fmt.Fprintf(sb, "_Astromech compliance ≥ human — no flag this month._\n\n")
	}
}

// writeArchHealthTrendSection is section 5 — month × rule_id matrix.
func writeArchHealthTrendSection(db *sql.DB, sb *strings.Builder, trendMonths []string) {
	fmt.Fprintf(sb, "## 5. 6-Month Trend\n\n")
	if len(trendMonths) == 0 {
		fmt.Fprintf(sb, "_No trend data yet._\n\n")
		return
	}

	// Pull aggregates for each month and pivot.
	type cell struct {
		month  string
		ruleID string
	}
	cells := map[cell]int{}
	ruleSet := map[string]bool{}
	for _, m := range trendMonths {
		mAggs, _ := store.ListArchHealthAggregatesForMonth(db, m)
		for _, a := range mAggs {
			cells[cell{month: m, ruleID: a.RuleID}] += a.ViolationCount
			ruleSet[a.RuleID] = true
		}
	}
	var rules []string
	for r := range ruleSet {
		rules = append(rules, r)
	}
	sort.Strings(rules)
	if len(rules) == 0 {
		fmt.Fprintf(sb, "_No rules have fired in the trailing 6 months._\n\n")
		return
	}

	fmt.Fprintf(sb, "| Rule")
	for _, m := range trendMonths {
		fmt.Fprintf(sb, " | %s", m)
	}
	fmt.Fprintf(sb, " |\n")
	fmt.Fprintf(sb, "|---")
	for range trendMonths {
		fmt.Fprintf(sb, "|---:")
	}
	fmt.Fprintf(sb, "|\n")
	for _, r := range rules {
		fmt.Fprintf(sb, "| %s", r)
		for _, m := range trendMonths {
			fmt.Fprintf(sb, " | %d", cells[cell{month: m, ruleID: r}])
		}
		fmt.Fprintf(sb, " |\n")
	}
	fmt.Fprintf(sb, "\n")
}

// writeArchHealthMethodology is section 6.
func writeArchHealthMethodology(sb *strings.Builder, weightsLoaded bool) {
	fmt.Fprintf(sb, "## 6. Methodology\n\n")
	fmt.Fprintf(sb, "- Scope: every `.go` file in every registered repo (excluding `vendor/`, `.git/`, `.force/`, `node_modules/`, `.d7-worktrees/`).\n")
	fmt.Fprintf(sb, "- Rules: every BoS rule whose FleetRules row is active (`category='bos'` AND `active_until=''`).\n")
	fmt.Fprintf(sb, "- Author classification: path-heuristic (v1):\n")
	fmt.Fprintf(sb, "  - `/migrations/` or `archaeologist_*` → `archaeologist-migration`\n")
	fmt.Fprintf(sb, "  - paths containing `astromech` → `astromech`\n")
	fmt.Fprintf(sb, "  - everything else → `human`\n")
	if weightsLoaded {
		fmt.Fprintf(sb, "- Weights: `docs/arch-health-weights.yaml` (FleetRule-adjacent — changes through D3 promotion pipeline).\n")
	} else {
		fmt.Fprintf(sb, "- Weights: weights file unavailable; defaulted to 1.0 per rule for this run.\n")
	}
	fmt.Fprintf(sb, "- Idempotence: `(report_month, rule_id, repo_id, author_type)` is UNIQUE; re-runs in the same month UPDATE the row's count rather than duplicating.\n")
}

// computeRepoHealthScore returns a per-repo score in [0, 100], higher =
// healthier. The score is `100 - clamp(weightedViolations, 0, 100)`
// where weightedViolations is sum_over_rules(count_in_repo * weight).
// A repo with zero violations scores 100; a repo with 100+ weighted
// violations floors at 0.
func computeRepoHealthScore(aggs []store.ArchHealthAggregate, repoID int, weights map[string]float64) float64 {
	var weighted float64
	for _, a := range aggs {
		if a.RepoID != repoID {
			continue
		}
		w := 1.0
		if v, ok := weights[a.RuleID]; ok {
			w = v
		}
		weighted += float64(a.ViolationCount) * w
	}
	score := 100.0 - weighted
	if score < 0 {
		score = 0
	}
	if score > 100 {
		score = 100
	}
	return score
}

// loadArchHealthWeights parses a tiny subset of the YAML schema:
//
//	weights:
//	  RULE-ID: <float>
//
// The parser is intentionally minimal — pulling in a YAML library for a
// 12-line file is overkill, and the format is fixed by the docs/
// header. Lines starting with `#` are comments; blank lines are
// ignored. Returns the map of rule_id → weight.
func loadArchHealthWeights(path string) (map[string]float64, error) {
	out := map[string]float64{}
	if path == "" {
		return out, fmt.Errorf("loadArchHealthWeights: empty path")
	}
	body, err := os.ReadFile(path)
	if err != nil {
		return out, fmt.Errorf("read %s: %w", path, err)
	}
	inWeights := false
	for _, raw := range strings.Split(string(body), "\n") {
		line := strings.TrimRight(raw, " \t")
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if trimmed == "weights:" {
			inWeights = true
			continue
		}
		if !inWeights {
			continue
		}
		// Lines under `weights:` are 2-space-indented `KEY: value` pairs.
		if !strings.HasPrefix(line, "  ") {
			// Top-level key — exit weights block.
			inWeights = false
			continue
		}
		colon := strings.Index(trimmed, ":")
		if colon < 0 {
			continue
		}
		key := strings.TrimSpace(trimmed[:colon])
		val := strings.TrimSpace(trimmed[colon+1:])
		var f float64
		if _, sErr := fmt.Sscanf(val, "%f", &f); sErr != nil {
			continue
		}
		out[key] = f
	}
	return out, nil
}

// trailingSixMonths returns the six month tokens (YYYY-MM) ending with
// `endMonth`. End is inclusive, ascending order.
func trailingSixMonths(endMonth string) []string {
	t, err := time.Parse("2006-01", endMonth)
	if err != nil {
		return nil
	}
	out := make([]string, 0, 6)
	for i := 5; i >= 0; i-- {
		out = append(out, t.AddDate(0, -i, 0).Format("2006-01"))
	}
	return out
}

// buildSparkline returns a 6-cell ASCII sparkline (▁▂▃▄▅▆▇█) for the
// given rule across trendMonths. Uses block characters so the report
// renders cleanly in any monospaced viewer.
func buildSparkline(db *sql.DB, ruleID string, trendMonths []string) string {
	if len(trendMonths) == 0 {
		return ""
	}
	counts := make([]int, len(trendMonths))
	for i, m := range trendMonths {
		mAggs, _ := store.ListArchHealthAggregatesForMonth(db, m)
		for _, a := range mAggs {
			if a.RuleID == ruleID {
				counts[i] += a.ViolationCount
			}
		}
	}
	maxV := 0
	for _, v := range counts {
		if v > maxV {
			maxV = v
		}
	}
	if maxV == 0 {
		return strings.Repeat("▁", len(counts))
	}
	bars := []rune{'▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'}
	var sb strings.Builder
	for _, v := range counts {
		idx := 0
		if v > 0 {
			// scale to 0..7
			idx = int(float64(v) / float64(maxV) * float64(len(bars)-1))
			if idx > len(bars)-1 {
				idx = len(bars) - 1
			}
		}
		sb.WriteRune(bars[idx])
	}
	return sb.String()
}

// distinctRules returns the count of distinct rule_id values across aggs.
func distinctRules(aggs []store.ArchHealthAggregate) int {
	seen := map[string]bool{}
	for _, a := range aggs {
		seen[a.RuleID] = true
	}
	return len(seen)
}

// ifEmpty returns def if s == "".
func ifEmpty(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
