// Package agents — rule_renderer.go: dispatch FleetRules rows to their
// physical render targets. Shape is a clean separation: each render target
// is one query + one assembler; no path bleeds into another.
package agents

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// ClaudeMdHardCapBytes is the hard cap on rendered CLAUDE.md output.
// 10 KB is the Phase 1 target; 20 KB is the absolute upper bound the
// pre-commit hook + CI Pattern test enforce. The renderer refuses to
// write a render exceeding this.
const ClaudeMdHardCapBytes = 20 * 1024

// renderHeader is prepended to every auto-generated rendered file so a
// human opening the file knows it's machine-managed.
const renderHeader = "<!-- AUTO-GENERATED by force render-rules from FleetRules table.\n" +
	"     Do not edit by hand. Edit the FleetRules row, then run `make render-rules`. -->\n\n"

// activeRule carries the in-memory shape of a rendered FleetRules row.
type activeRule struct {
	RuleKey    string
	Category   string
	AgentScope string
	RenderTo   string
	EnforcedBy string
	Content    string
}

func selectActiveRules(ctx context.Context, db *sql.DB, where string, args ...any) ([]activeRule, error) {
	q := `SELECT rule_key, category, agent_scope, render_to, enforced_by, content
		FROM FleetRules
		WHERE active_until = '' AND ` + where + `
		ORDER BY category, rule_key`
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("select FleetRules: %w", err)
	}
	defer rows.Close()
	var out []activeRule
	for rows.Next() {
		var r activeRule
		if err := rows.Scan(&r.RuleKey, &r.Category, &r.AgentScope, &r.RenderTo, &r.EnforcedBy, &r.Content); err != nil {
			return nil, fmt.Errorf("scan FleetRules row: %w", err)
		}
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate FleetRules: %w", err)
	}
	return out, nil
}

// RenderClaudeMdFile produces the CLAUDE.md bytes (universal-load file).
// Returns an error and emits operator mail if the rendered output
// exceeds the hard cap — the renderer refuses to write garbage.
func RenderClaudeMdFile(ctx context.Context, db *sql.DB) ([]byte, error) {
	rules, err := selectActiveRules(ctx, db, `render_to = 'claude-md-file'`)
	if err != nil {
		return nil, err
	}
	body := assembleClaudeMd(rules)
	if len(body) > ClaudeMdHardCapBytes {
		return nil, fmt.Errorf("[RULE-RENDERER OVERFLOW] rendered CLAUDE.md is %d bytes; hard cap is %d", len(body), ClaudeMdHardCapBytes)
	}
	return body, nil
}

// RenderFixLog produces the FIX-LOG.md bytes from the historical-narrative
// rules. Append-only narrative; no size cap (FIX-LOG.md is operator-browsed,
// not auto-loaded).
//
// D3-P1 follow-up C: the rendered file now carries the AUTO-GENERATED
// preamble (every operator who opens FIX-LOG.md sees it is machine-
// managed) plus the historic intro paragraph that used to live above
// the first ## Fix entry. Drift detection via CheckRenderDrift covers
// FIX-LOG.md by default once the audit owns every narrative.
func RenderFixLog(ctx context.Context, db *sql.DB) ([]byte, error) {
	rules, err := selectActiveRules(ctx, db, `render_to = 'fix-log'`)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString(renderHeader)
	b.WriteString("# Fix Log\n\n")
	b.WriteString("Operator narrative for each audit-fix PR. ")
	b.WriteString("Written as each fix merges to main. ")
	b.WriteString("Each entry answers: what broke, what shipped, how it was proved, what to watch for next.\n\n")
	for i, r := range rules {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(strings.TrimRight(r.Content, "\n"))
		b.WriteString("\n")
	}
	return []byte(b.String()), nil
}

// RenderPerDomainDocs produces a map of filename → content bytes from the
// per-domain-doc:* rules. The filename is taken from the suffix after the
// colon (e.g. `per-domain-doc:docs/dashboard-conventions.md` →
// `docs/dashboard-conventions.md`).
func RenderPerDomainDocs(ctx context.Context, db *sql.DB) (map[string][]byte, error) {
	rules, err := selectActiveRules(ctx, db, `render_to LIKE 'per-domain-doc:%'`)
	if err != nil {
		return nil, err
	}
	grouped := map[string][]activeRule{}
	for _, r := range rules {
		path := strings.TrimPrefix(r.RenderTo, "per-domain-doc:")
		if path == "" {
			continue
		}
		grouped[path] = append(grouped[path], r)
	}
	out := map[string][]byte{}
	for path, group := range grouped {
		// Stable order: sort by (category, rule_key).
		sort.Slice(group, func(i, j int) bool {
			if group[i].Category != group[j].Category {
				return group[i].Category < group[j].Category
			}
			return group[i].RuleKey < group[j].RuleKey
		})
		var b strings.Builder
		b.WriteString(renderHeader)
		for i, r := range group {
			if i > 0 {
				b.WriteString("\n\n")
			}
			b.WriteString(r.Content)
		}
		b.WriteString("\n")
		out[path] = []byte(b.String())
	}
	return out, nil
}

// AssemblePerAgentPrompt returns the concatenated content of every
// active FleetRule with render_to='agent-prompt' that applies to the
// given agent. Applies the spec's three-way scope filter:
//   - agent_scope = 'all'
//   - agent_scope = <agent>
//   - <agent> appears in a comma-separated agent_scope list
// Result is ready to append to a system prompt; empty string when no
// rules match.
func AssemblePerAgentPrompt(ctx context.Context, db *sql.DB, agent string) (string, error) {
	q := `SELECT content FROM FleetRules
		WHERE active_until = '' AND render_to = 'agent-prompt'
		  AND (
		      agent_scope = 'all'
		      OR agent_scope = ?
		      OR ',' || agent_scope || ',' LIKE '%,' || ? || ',%'
		  )
		ORDER BY category, rule_key`
	rows, err := db.QueryContext(ctx, q, agent, agent)
	if err != nil {
		return "", fmt.Errorf("select agent-prompt rules: %w", err)
	}
	defer rows.Close()
	var b strings.Builder
	first := true
	for rows.Next() {
		var content string
		if err := rows.Scan(&content); err != nil {
			return "", fmt.Errorf("scan agent-prompt row: %w", err)
		}
		if !first {
			b.WriteString("\n\n")
		}
		b.WriteString(content)
		first = false
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate agent-prompt rows: %w", err)
	}
	return b.String(), nil
}

// WriteRenderedClaudeMd writes the rendered output to the given path.
// Idempotent: if the rendered bytes match what's on disk (by SHA256),
// the file is not touched (preserves mtime). Returns the bytes written
// and a bool indicating whether the file changed.
func WriteRenderedClaudeMd(ctx context.Context, db *sql.DB, path string) (int, bool, error) {
	body, err := RenderClaudeMdFile(ctx, db)
	if err != nil {
		return 0, false, err
	}
	existing, _ := os.ReadFile(path)
	if sameContent(existing, body) {
		return len(body), false, nil
	}
	if err := os.WriteFile(path, body, 0o644); err != nil {
		return 0, false, fmt.Errorf("write %s: %w", path, err)
	}
	return len(body), true, nil
}

// WriteRenderedFixLog mirrors WriteRenderedClaudeMd for FIX-LOG.md.
func WriteRenderedFixLog(ctx context.Context, db *sql.DB, path string) (int, bool, error) {
	body, err := RenderFixLog(ctx, db)
	if err != nil {
		return 0, false, err
	}
	existing, _ := os.ReadFile(path)
	if sameContent(existing, body) {
		return len(body), false, nil
	}
	if err := os.WriteFile(path, body, 0o644); err != nil {
		return 0, false, fmt.Errorf("write %s: %w", path, err)
	}
	return len(body), true, nil
}

// WriteRenderedPerDomainDocs writes every per-domain doc to its target
// path under repoRoot. Returns the per-path byte counts and a list of
// paths that actually changed.
func WriteRenderedPerDomainDocs(ctx context.Context, db *sql.DB, repoRoot string) (map[string]int, []string, error) {
	docs, err := RenderPerDomainDocs(ctx, db)
	if err != nil {
		return nil, nil, err
	}
	sizes := map[string]int{}
	var changed []string
	for relPath, body := range docs {
		full := relPath
		if !strings.HasPrefix(full, "/") {
			full = repoRoot + "/" + relPath
		}
		if dir := dirOf(full); dir != "" {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return nil, nil, fmt.Errorf("mkdir %s: %w", dir, err)
			}
		}
		existing, _ := os.ReadFile(full)
		sizes[relPath] = len(body)
		if sameContent(existing, body) {
			continue
		}
		if err := os.WriteFile(full, body, 0o644); err != nil {
			return nil, nil, fmt.Errorf("write %s: %w", full, err)
		}
		changed = append(changed, relPath)
	}
	return sizes, changed, nil
}

// CheckRenderDrift renders every target in memory and compares to disk.
// Returns the list of paths whose on-disk content differs from the
// rendered bytes. Used by `force render-rules --check` and the
// pre-commit hook to refuse hand-edits to auto-generated files.
//
// D3-P1 follow-up C: FIX-LOG.md is included by default. Phase 1's
// initial audit only covered ~5 fix narratives so the file was
// excluded behind a flag; the audit now owns every narrative
// (verified by the bootstrap parity tests), so drift detection is
// safe and operator-friendly.
func CheckRenderDrift(ctx context.Context, db *sql.DB, repoRoot string) ([]string, error) {
	var diverged []string

	claudeMd, err := RenderClaudeMdFile(ctx, db)
	if err != nil {
		return nil, err
	}
	if existing, _ := os.ReadFile(repoRoot + "/CLAUDE.md"); !sameContent(existing, claudeMd) {
		diverged = append(diverged, "CLAUDE.md")
	}

	fixLog, err := RenderFixLog(ctx, db)
	if err != nil {
		return nil, err
	}
	if existing, _ := os.ReadFile(repoRoot + "/FIX-LOG.md"); !sameContent(existing, fixLog) {
		diverged = append(diverged, "FIX-LOG.md")
	}

	docs, err := RenderPerDomainDocs(ctx, db)
	if err != nil {
		return nil, err
	}
	for relPath, body := range docs {
		full := relPath
		if !strings.HasPrefix(full, "/") {
			full = repoRoot + "/" + relPath
		}
		if existing, _ := os.ReadFile(full); !sameContent(existing, body) {
			diverged = append(diverged, relPath)
		}
	}
	sort.Strings(diverged)
	return diverged, nil
}

// assembleClaudeMd produces the markdown body for the universal-load
// CLAUDE.md file. Sections are grouped by category and ordered for
// stable output.
func assembleClaudeMd(rules []activeRule) []byte {
	sort.Slice(rules, func(i, j int) bool {
		if rules[i].Category != rules[j].Category {
			return rules[i].Category < rules[j].Category
		}
		return rules[i].RuleKey < rules[j].RuleKey
	})

	var b strings.Builder
	b.WriteString(renderHeader)
	b.WriteString("# CLAUDE.md — directives for agents working on this codebase\n\n")
	b.WriteString("Auto-rendered from FleetRules where `render_to='claude-md-file'`. ")
	b.WriteString("Domain-specific rules live under `docs/`; per-agent rules are injected ")
	b.WriteString("via `--append-system-prompt`; fix narratives live in `FIX-LOG.md`.\n\n")
	b.WriteString("To add a universal-load rule: insert a FleetRules row with `render_to='claude-md-file'` ")
	b.WriteString("AND a justification comment in `internal/store/fleet_rules_audit.go`, then `make render-rules`.\n\n")

	currentCategory := ""
	for _, r := range rules {
		if r.Category != currentCategory {
			currentCategory = r.Category
			b.WriteString("\n## " + categoryHeading(r.Category) + "\n\n")
		}
		b.WriteString(r.Content)
		b.WriteString("\n\n")
	}

	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}

// categoryHeading turns a category tag into a human-readable heading.
func categoryHeading(category string) string {
	switch category {
	case "architecture":
		return "Architecture invariants"
	case "schema":
		return "Schema conventions"
	case "security":
		return "Security invariants"
	case "testing":
		return "Testing rules"
	case "process":
		return "Commit + process discipline"
	case "self-healing":
		return "Self-healing invariants"
	case "pr-flow":
		return "PR flow invariants"
	case "dashboard":
		return "Dashboard invariants"
	case "llm-prompt-discipline":
		return "LLM prompt discipline"
	case "fix-narrative":
		return "Historical fix narratives"
	default:
		return strings.ToUpper(category[:1]) + category[1:]
	}
}

func sameContent(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	ha := sha256.Sum256(a)
	hb := sha256.Sum256(b)
	return hex.EncodeToString(ha[:]) == hex.EncodeToString(hb[:])
}

func dirOf(path string) string {
	idx := strings.LastIndex(path, "/")
	if idx <= 0 {
		return ""
	}
	return path[:idx]
}

// renderToWriter is exposed for the CLI sub-command's --check flag and
// for tests that want to compare in-memory output to a buffer.
func renderToWriter(w io.Writer, body []byte) (int, error) {
	return w.Write(body)
}
