package precommit_test

// D10 — pre-commit hook scratch tests.
//
// Mirror of the onboarding-md-check pattern: drive the
// architecture-md-check.sh hook against synthetic staged blobs in a
// temp git repo and assert the exit codes.
//
// Skipped when bash or git is unavailable on the host.

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func locateHook(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("runtime.Caller failed")
	}
	return filepath.Join(filepath.Dir(thisFile), "architecture-md-check.sh")
}

func skipIfMissing(t *testing.T, bin string) {
	t.Helper()
	if _, err := exec.LookPath(bin); err != nil {
		t.Skipf("%s not in PATH — skipping integration test", bin)
	}
}

func newTempGitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	envInit := append(os.Environ(),
		"GIT_AUTHOR_NAME=Test",
		"GIT_AUTHOR_EMAIL=t@t.com",
		"GIT_COMMITTER_NAME=Test",
		"GIT_COMMITTER_EMAIL=t@t.com",
	)
	run := func(args ...string) {
		t.Helper()
		cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
		cmd.Env = envInit
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %s", args, out)
		}
	}
	run("init", "-b", "main")
	run("config", "user.email", "t@t.com")
	run("config", "user.name", "Test")
	if err := os.WriteFile(filepath.Join(dir, "seed.txt"), []byte("seed\n"), 0644); err != nil {
		t.Fatalf("write seed: %v", err)
	}
	run("add", "seed.txt")
	run("commit", "-m", "seed")
	return dir
}

func runHook(t *testing.T, dir, hookPath string) (int, string) {
	t.Helper()
	cmd := exec.Command("bash", hookPath)
	cmd.Dir = dir
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	err := cmd.Run()
	if err == nil {
		return 0, out.String()
	}
	if exitErr, ok := err.(*exec.ExitError); ok {
		return exitErr.ExitCode(), out.String()
	}
	t.Fatalf("hook exec failed: %v", err)
	return -1, out.String()
}

// TestArchitectureMdHook_NoStagedFile_ExitsZero confirms a normal
// commit (no ARCHITECTURE.md staged) exits 0.
func TestArchitectureMdHook_NoStagedFile_ExitsZero(t *testing.T) {
	skipIfMissing(t, "git")
	skipIfMissing(t, "bash")

	dir := newTempGitRepo(t)
	hook := locateHook(t)
	code, out := runHook(t, dir, hook)
	if code != 0 {
		t.Errorf("expected exit 0 with no staged ARCHITECTURE.md; got %d, out=%s", code, out)
	}
}

// TestArchitectureMdHook_StagedWithoutHeader_Rejects covers the
// hard-reject path: a hand-edited ARCHITECTURE.md without the
// AUTO-GENERATED header trips the hook with exit 1.
func TestArchitectureMdHook_StagedWithoutHeader_Rejects(t *testing.T) {
	skipIfMissing(t, "git")
	skipIfMissing(t, "bash")

	dir := newTempGitRepo(t)
	if err := os.WriteFile(filepath.Join(dir, "ARCHITECTURE.md"),
		[]byte("# Hand-edited!\n\nNo header here.\n"), 0644); err != nil {
		t.Fatalf("write: %v", err)
	}
	cmd := exec.Command("git", "-C", dir, "add", "ARCHITECTURE.md")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git add: %s", out)
	}
	hook := locateHook(t)
	code, out := runHook(t, dir, hook)
	if code != 1 {
		t.Errorf("expected exit 1 (reject); got %d, out=%s", code, out)
	}
	if !strings.Contains(out, "REJECT") {
		t.Errorf("expected 'REJECT' in stderr; got %q", out)
	}
}

// TestArchitectureMdHook_StagedWithHeader_Accepts covers the happy
// path: a renderer-produced ARCHITECTURE.md with the AUTO-GENERATED
// first line passes the hook.
func TestArchitectureMdHook_StagedWithHeader_Accepts(t *testing.T) {
	skipIfMissing(t, "git")
	skipIfMissing(t, "bash")

	dir := newTempGitRepo(t)
	body := "<!-- AUTO-GENERATED by `dogArchitectureDocRender` on 2026-05-02; DO NOT HAND-EDIT. -->\n\n# ARCHITECTURE — sample\n"
	if err := os.WriteFile(filepath.Join(dir, "ARCHITECTURE.md"),
		[]byte(body), 0644); err != nil {
		t.Fatalf("write: %v", err)
	}
	cmd := exec.Command("git", "-C", dir, "add", "ARCHITECTURE.md")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git add: %s", out)
	}
	hook := locateHook(t)
	code, out := runHook(t, dir, hook)
	if code != 0 {
		t.Errorf("expected exit 0 (accept); got %d, out=%s", code, out)
	}
}
