#!/usr/bin/env bash
# scripts/pre-commit/arch-health-md-check.sh
#
# D9 ArchHealth — pre-commit hook: refuse hand-edits to
# reports/architecture-health-*.md files.
#
# Mirrors scripts/pre-commit/onboarding-md-check.sh: any staged file
# matching reports/architecture-health-*.md MUST carry the
# AUTO-GENERATED header that the renderer in
# internal/agents/dogs_arch_health_render.go writes. Hand-edits drift
# the report away from the canonical ArchHealthAggregates view, which
# defeats the longitudinal-trend purpose of the report.
#
# Anti-cheat (docs/roadmap.md § D9 — "No health-report metric
# inflation"): the report's content is dictated by the dog. If the
# operator wants to comment on the data, the right path is an
# operator-event annotation (POST /api/annotations) or a separate
# Markdown file under docs/ — not editing the auto-generated output.
#
# Exit codes:
#   0 — no architecture-health-*.md staged OR every staged file carries
#       the AUTO-GENERATED header
#   1 — hard reject (a staged file was hand-edited)
#   2 — pre-flight failure (not in a git repo)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$REPO_ROOT" ]]; then
  printf 'arch-health-md-check: must run from inside a git repo\n' >&2
  exit 2
fi

cd "$REPO_ROOT"

# Match reports/architecture-health-*.md in the staged set. The report
# directory is `reports/`; the renderer writes
# architecture-health-YYYY-MM.md. We match the full path glob (not just
# basename) because the file is always under reports/.
staged_paths=()
while IFS= read -r path; do
  case "$path" in
    reports/architecture-health-*.md)
      staged_paths+=("$path")
      ;;
  esac
done < <(git diff --cached --name-only --diff-filter=ACM)

if [[ ${#staged_paths[@]} -eq 0 ]]; then
  exit 0
fi

# Each staged report must have its first staged line start with the
# AUTO-GENERATED prefix that the renderer emits. We read the *staged*
# blob (not the on-disk file) so a hand-edit-then-add is detected even
# if the working tree no longer reflects it.
expected_prefix='<!-- AUTO-GENERATED by `force dog architecture-health-report'
violations=()
for path in "${staged_paths[@]}"; do
  first_line="$(git show ":${path}" 2>/dev/null | head -n 1 || true)"
  if [[ "$first_line" != ${expected_prefix}* ]]; then
    violations+=("$path")
  fi
done

if [[ ${#violations[@]} -eq 0 ]]; then
  exit 0
fi

printf '\n' >&2
printf 'arch-health-md-check: REJECT — hand-edited architecture-health report detected.\n' >&2
printf '\n' >&2
printf '  The following staged file(s) do NOT carry the AUTO-GENERATED header:\n' >&2
for v in "${violations[@]}"; do
  printf '    - %s\n' "$v" >&2
done
printf '\n' >&2
printf '  Architecture health reports are renderer-output only. Re-run the dog:\n' >&2
printf '\n' >&2
printf '    force dogs run architecture-health-report\n' >&2
printf '\n' >&2
printf '  Then re-stage the renderer-produced file. If you intended to comment on\n' >&2
printf '  the data, add an operator-event annotation (POST /api/annotations) or\n' >&2
printf '  document the observation under docs/, not in the report itself.\n' >&2

exit 1
