#!/usr/bin/env bash
# scripts/pre-commit/onboarding-md-check.sh
#
# D6 — pre-commit hook: refuse hand-edits to ONBOARDING.md files.
#
# Behaviour: if any path matching ONBOARDING.md (root-level or under
# any subdirectory) is staged AND the file's first line does not
# start with the AUTO-GENERATED header `force onboard` writes, the
# commit is rejected.
#
# The intent mirrors the CLAUDE.md pattern (claude-md-size-check.sh):
# auto-generated artefacts must round-trip through the renderer, not
# the operator's editor. ONBOARDING.md is operator-triggered (the CLI
# is on-demand, not a dog), so the orchestrator's own ONBOARDING.md is
# .gitignore'd by default — but if the operator explicitly stages one
# (e.g. for a closure-report sample), the staged content MUST carry the
# header so reviewers can see the file came from the renderer.
#
# Exit codes:
#   0 — no ONBOARDING.md staged OR every staged ONBOARDING.md carries
#       the AUTO-GENERATED header
#   1 — hard reject (a staged ONBOARDING.md was hand-edited)
#   2 — pre-flight failure

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$REPO_ROOT" ]]; then
  printf 'onboarding-md-check: must run from inside a git repo\n' >&2
  exit 2
fi

cd "$REPO_ROOT"

# Match ONBOARDING.md at any depth in the staged set. Use newline-
# delimited output so paths with spaces (rare but legal) are handled.
staged_paths=()
while IFS= read -r path; do
  case "$(basename -- "$path")" in
    ONBOARDING.md)
      staged_paths+=("$path")
      ;;
  esac
done < <(git diff --cached --name-only --diff-filter=ACM)

if [[ ${#staged_paths[@]} -eq 0 ]]; then
  exit 0
fi

# Each staged ONBOARDING.md must have its first staged line start with
# the AUTO-GENERATED prefix that `force onboard` emits. We read the
# *staged* blob (not the on-disk file) so a hand-edit-then-add is
# detected even if the working tree no longer reflects it.
expected_prefix='<!-- AUTO-GENERATED by `force onboard'
violations=()
for path in "${staged_paths[@]}"; do
  first_line="$(git show ":${path}" 2>/dev/null | head -n 1 || true)"
  if [[ "$first_line" != ${expected_prefix}* ]]; then
    violations+=("$path")
  fi
done

if [[ ${#violations[@]} -eq 0 ]]; then
  exit 0
fi

printf '\n' >&2
printf 'onboarding-md-check: REJECT — hand-edited ONBOARDING.md detected.\n' >&2
printf '\n' >&2
printf '  The following staged file(s) do NOT carry the AUTO-GENERATED header:\n' >&2
for v in "${violations[@]}"; do
  printf '    - %s\n' "$v" >&2
done
printf '\n' >&2
printf '  ONBOARDING.md is operator-rendered by `force onboard <repo>`.\n' >&2
printf '  Hand-edits are not allowed; re-run the renderer:\n' >&2
printf '\n' >&2
printf '    force onboard --refresh <repo>\n' >&2
printf '\n' >&2
printf '  If you intended to commit a renderer-produced sample (e.g. for a\n' >&2
printf '  closure-report), confirm the renderer wrote the AUTO-GENERATED\n' >&2
printf '  header at the top of the file before re-staging.\n' >&2

exit 1
