// Package librarian — D10 BuildArchitectureDoc implementation.
//
// BuildArchitectureDoc is the architecture-level rendering primitive
// consumed by `dogArchitectureDocRender` on every merge to main of
// an enabled repo. The implementation reuses BuildRepoDigest so the
// digest-assembly seam stays collapsed (mirrors D6's BuildRepoDigest
// shared-seam pattern between SenatorOnboarding and `force onboard`).
//
// Anti-cheat #2 (no ARCHITECTURE.md duplicating CLAUDE.md): this
// renderer deliberately consumes the digest's RepoDigest.Conventions
// map only for the "Common conventions" pointer — it never inlines
// any CLAUDE.md text. `TestArchitectureMdNotDuplicateOfClaudeMd`
// asserts the invariant against a synthetic fixture pair.
package librarian

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"
)

// architectureDocAutoGeneratedHeaderPrefix is the literal prefix of
// the AUTO-GENERATED comment stamped at the top of every
// ARCHITECTURE.md. The pre-commit hook compares the staged file's
// first line against this prefix to detect hand-edits.
const architectureDocAutoGeneratedHeaderPrefix = "<!-- AUTO-GENERATED by `dogArchitectureDocRender`"

// BuildArchitectureDoc renders the ARCHITECTURE.md body for the
// supplied repo. Pure-data: returns the Markdown body + path; the
// caller (the dog) writes to disk.
func (c *inProcessClient) BuildArchitectureDoc(ctx context.Context, repoSpec string) (ArchitectureDoc, error) {
	if err := ctx.Err(); err != nil {
		return ArchitectureDoc{}, err
	}
	digest, err := c.BuildRepoDigest(ctx, repoSpec)
	if err != nil {
		return ArchitectureDoc{}, fmt.Errorf("librarian: BuildArchitectureDoc: %w", err)
	}
	displayName := digest.RepoName
	if displayName == "" {
		displayName = filepath.Base(digest.LocalPath)
	}
	body := renderArchitectureMarkdown(digest, displayName)
	return ArchitectureDoc{
		RepoName:    digest.RepoName,
		LocalPath:   digest.LocalPath,
		Markdown:    body,
		GeneratedAt: digest.GeneratedAt,
	}, nil
}

// renderArchitectureMarkdown shapes a RepoDigest into the
// architecture-level Markdown body. Sections (in order):
//
//  1. AUTO-GENERATED header
//  2. Title
//  3. ## Subsystem map
//  4. ## Public interfaces
//  5. ## Recent activity (architectural pulse)
//  6. ## Deployment + data shape
//  7. ## Pointers (CLAUDE.md / CONTRIBUTING.md / SENATE.md)
//
// Anti-cheat #2 enforcement: the "Pointers" section is intentionally
// a 1-line "see <file>" reference per conventions file — NOT an
// inlined excerpt. Tests assert no contiguous run > 80 chars
// verbatim from CLAUDE.md.
func renderArchitectureMarkdown(d RepoDigest, displayName string) string {
	var b strings.Builder
	dateOnly := d.GeneratedAt
	if len(dateOnly) >= 10 {
		dateOnly = dateOnly[:10]
	}
	fmt.Fprintf(&b, "%s on %s; DO NOT HAND-EDIT. The dog regenerates this file on every merge to main. -->\n\n",
		architectureDocAutoGeneratedHeaderPrefix, dateOnly)
	fmt.Fprintf(&b, "# ARCHITECTURE — %s\n\n", displayName)
	b.WriteString("_Architecture-level narrative. Invariants live in CLAUDE.md; this doc is the system map._\n\n")

	// Subsystem map (top-level dirs).
	b.WriteString("## Subsystem map\n\n")
	if len(d.TopLevelDirs) == 0 {
		b.WriteString("_No top-level directories detected; the repo may be brand-new._\n\n")
	} else {
		b.WriteString("Top-level packages and their role at a glance:\n\n")
		for _, dir := range d.TopLevelDirs {
			fmt.Fprintf(&b, "- **`%s/`** — top-level subsystem. Open it to inspect the module's entry points and tests.\n", dir)
		}
		b.WriteString("\n")
	}

	// Public interfaces (architecture-level — interfaces, HTTP, CLI).
	b.WriteString("## Public interfaces\n\n")
	if len(d.PublicAPISymbols) == 0 {
		b.WriteString("_No exported interfaces, HTTP routes, or CLI subcommands surfaced by the lightweight scan._\n\n")
	} else {
		groups := map[string][]APISymbol{}
		for _, s := range d.PublicAPISymbols {
			groups[s.Kind] = append(groups[s.Kind], s)
		}
		emit := func(label, kind string) {
			entries, ok := groups[kind]
			if !ok || len(entries) == 0 {
				return
			}
			fmt.Fprintf(&b, "**%s** (%d surfaced):\n\n", label, len(entries))
			for _, e := range entries {
				fmt.Fprintf(&b, "- `%s` — %s\n", e.Name, e.Description)
			}
			b.WriteString("\n")
		}
		emit("Exported Go interfaces", "interface")
		emit("HTTP routes", "http")
		emit("CLI subcommands", "cli")
	}

	// Recent activity (architectural pulse).
	b.WriteString("## Recent activity\n\n")
	commits := d.RecentCommits.Commits
	if len(commits) == 0 {
		b.WriteString("_No commits in the trailing 90-day window._\n\n")
	} else {
		fmt.Fprintf(&b, "Trailing 90-day pulse: **%d commits**", len(commits))
		if d.RecentCommits.Truncated {
			b.WriteString(" (digest truncated at the per-call cap)")
		}
		b.WriteString(".\n\n")
		// Newest 5 subjects.
		max := 5
		if len(commits) < max {
			max = len(commits)
		}
		b.WriteString("Newest commits:\n\n")
		for i := 0; i < max; i++ {
			c := commits[i]
			short := c.SHA
			if len(short) > 7 {
				short = short[:7]
			}
			fmt.Fprintf(&b, "- `%s` — %s _(%s)_\n", short, c.Subject, c.Author)
		}
		b.WriteString("\n")
	}

	// Deployment + data shape (intentionally light — pulls from
	// description + README sample's first paragraph).
	b.WriteString("## Deployment + data shape\n\n")
	if strings.TrimSpace(d.Description) != "" {
		b.WriteString(strings.TrimSpace(d.Description))
		b.WriteString("\n\n")
	} else if first := firstReadmeParagraphForArchitecture(d.READMESample); first != "" {
		b.WriteString(first)
		b.WriteString("\n\n")
	} else {
		b.WriteString("_No registered description or README excerpt available._\n\n")
	}

	// Pointers — anti-cheat #2: 1-line reference each, NEVER inline
	// excerpts. CLAUDE.md is the invariants doc; this section just
	// points reviewers there.
	b.WriteString("## Pointers\n\n")
	b.WriteString("Authoritative companion documents for this repo:\n\n")
	emitted := false
	for _, name := range []string{"CLAUDE.md", "CONTRIBUTING.md", "SENATE.md"} {
		body := strings.TrimSpace(d.Conventions[name])
		if body == "" {
			continue
		}
		emitted = true
		fmt.Fprintf(&b, "- **`%s`** — see the file at the repo root.\n", name)
	}
	if !emitted {
		b.WriteString("- _None of `CLAUDE.md`, `CONTRIBUTING.md`, `SENATE.md` are present at the repo root._\n")
	}

	return b.String()
}

// firstReadmeParagraphForArchitecture is a copy of the onboarding
// CLI's helper, scoped to this package so we don't introduce a
// cross-package dependency. Heuristic: skip leading blanks +
// headings, then take everything up to the next blank line.
func firstReadmeParagraphForArchitecture(readme string) string {
	lines := strings.Split(readme, "\n")
	var collected []string
	started := false
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if !started {
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			started = true
			collected = append(collected, trimmed)
			continue
		}
		if trimmed == "" {
			break
		}
		collected = append(collected, trimmed)
	}
	if len(collected) == 0 {
		return ""
	}
	return strings.Join(collected, " ")
}
