package librarian

// D10 — BuildArchitectureDoc tests.
//
// Coverage:
//   - End-to-end render against a synthetic on-disk repo: the
//     emitted Markdown carries the AUTO-GENERATED header, includes
//     the subsystem map, and points to (does not inline) CLAUDE.md.
//   - Anti-cheat #2: TestArchitectureMdNotDuplicateOfClaudeMd — for
//     a synthetic fixture pair (a CLAUDE.md with distinctive long
//     lines + the rendered ARCHITECTURE.md) no contiguous run > 80
//     chars from CLAUDE.md appears verbatim in ARCHITECTURE.md.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestBuildArchitectureDoc_RendersHeaderAndStructure runs
// BuildArchitectureDoc against an on-disk synthetic repo and asserts
// the rendered Markdown carries the AUTO-GENERATED header + the
// canonical section list.
func TestBuildArchitectureDoc_RendersHeaderAndStructure(t *testing.T) {
	dir := t.TempDir()
	mustWriteFile(t, filepath.Join(dir, "README.md"), "# Synthetic\n\nA test repo for D10.\n")
	if err := os.MkdirAll(filepath.Join(dir, "internal"), 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "cmd"), 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	mustWriteFile(t, filepath.Join(dir, "CLAUDE.md"), "# CLAUDE.md\n\nInvariants.\n")

	c := &inProcessClient{db: nil}
	doc, err := c.BuildArchitectureDoc(context.Background(), dir)
	if err != nil {
		t.Fatalf("BuildArchitectureDoc: %v", err)
	}
	if !strings.HasPrefix(doc.Markdown, architectureDocAutoGeneratedHeaderPrefix) {
		t.Errorf("body does not start with AUTO-GENERATED header; first 80 bytes=%q",
			truncForLog(doc.Markdown, 80))
	}
	for _, want := range []string{
		"## Subsystem map",
		"## Public interfaces",
		"## Recent activity",
		"## Deployment + data shape",
		"## Pointers",
	} {
		if !strings.Contains(doc.Markdown, want) {
			t.Errorf("rendered Markdown missing section heading %q", want)
		}
	}
	// Anti-cheat #2: the body must NOT inline CLAUDE.md content. We
	// pointed at it, but the renderer's "Pointers" section must not
	// embed the file.
	if strings.Contains(doc.Markdown, "Invariants.") {
		t.Errorf("ARCHITECTURE.md inlined a CLAUDE.md fragment — anti-cheat #2 violated")
	}
	if doc.LocalPath != dir {
		t.Errorf("LocalPath = %q, want %q", doc.LocalPath, dir)
	}
}

// TestArchitectureMdNotDuplicateOfClaudeMd is the anti-cheat #2
// regression. We construct a CLAUDE.md whose body contains several
// distinctive long lines (>80 chars each) and then render
// ARCHITECTURE.md against the same synthetic repo. No contiguous
// >80-char substring from CLAUDE.md may appear in ARCHITECTURE.md.
//
// The threshold (80 chars) is the roadmap's spec: "no contiguous
// text run > 80 chars verbatim from CLAUDE.md."
func TestArchitectureMdNotDuplicateOfClaudeMd(t *testing.T) {
	dir := t.TempDir()
	// Distinctive 120-char lines — three of them, well above the
	// 80-char threshold. Any leak shows up unambiguously.
	claudeBody := strings.Join([]string{
		"# CLAUDE.md — directives for agents working on this codebase",
		"",
		"distinctive-claude-md-line-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
		"",
		"distinctive-claude-md-line-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"",
		"distinctive-claude-md-line-ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
		"",
	}, "\n")
	mustWriteFile(t, filepath.Join(dir, "CLAUDE.md"), claudeBody)
	mustWriteFile(t, filepath.Join(dir, "README.md"), "# Synthetic\n\nA repo for the anti-cheat test.\n")

	c := &inProcessClient{db: nil}
	doc, err := c.BuildArchitectureDoc(context.Background(), dir)
	if err != nil {
		t.Fatalf("BuildArchitectureDoc: %v", err)
	}

	// Walk every contiguous run of length > 80 from CLAUDE.md and
	// ensure none appear verbatim in ARCHITECTURE.md.
	const window = 81
	if violation := findClaudeLeak(claudeBody, doc.Markdown, window); violation != "" {
		t.Errorf("ARCHITECTURE.md contains a >%d-char contiguous run from CLAUDE.md: %q",
			window-1, truncForLog(violation, 120))
	}
}

// findClaudeLeak returns the first window-character substring of
// claude that appears verbatim in arch, or "" if none. window must
// be > 0; the natural threshold is 81 for the >80-char rule.
func findClaudeLeak(claude, arch string, window int) string {
	if len(claude) <= window || arch == "" {
		return ""
	}
	for i := 0; i+window <= len(claude); i++ {
		// Skip runs that consist solely of whitespace / newline —
		// these are spuriously common (e.g. multiple blank lines)
		// and don't represent real content leaks.
		run := claude[i : i+window]
		if strings.TrimSpace(run) == "" {
			continue
		}
		if strings.Contains(arch, run) {
			return run
		}
	}
	return ""
}

func mustWriteFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func truncForLog(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
